smeup/ketchup

packages/ketchup-showcase/src/views/dataTable/DTRowSelection.vue, packages/ketchup/src/components.d.ts, packages/ketchup/src/components/ketchup-dash/readme.md, packages/ketchup/src/components/ketchup-data-table/ketchup-data-table.scss, packages/ketchup/src/components/ketchup-data-table/ketchup-data-table.tsx, packages/ketchup/src/components/ketchup-data-table/readme.md
- Row density test
- fix multiselection
- Auto row select event
=> Data table minor fixes

packages/ketchup-showcase/src/App.vue, packages/ketchup-showcase/src/mock/dataTable.ts, packages/ketchup-showcase/src/plugins/router/dataTable.ts, packages/ketchup-showcase/src/views/dataTable/DTBasic.vue, packages/ketchup-showcase/src/views/dataTable/DTRowActions.vue, packages/ketchup/package-lock.json, packages/ketchup/src/components.d.ts, packages/ketchup/src/components/ketchup-data-table/ketchup-data-table-declarations.ts, packages/ketchup/src/components/ketchup-data-table/ketchup-data-table.scss, packages/ketchup/src/components/ketchup-data-table/ketchup-data-table.tsx, packages/ketchup/src/components/ketchup-data-table/readme.md, packages/ketchup/src/utils/object-utils.ts, packages/ketchup/tests/e2e/data-table/data-table-basic.e2e.ts, packages/ketchup/tests/e2e/data-table/data-table-grouping.e2e.ts, packages/ketchup/tests/e2e/data-table/data-table-sort.e2e.ts, packages/ketchup/tests/e2e/data-table/mocked-data.ts
=> Kup data table: icons / images / row actions

packages/ketchup/src/components.d.ts, packages/ketchup/src/components/ketchup-data-table/ketchup-data-table-declarations.ts, packages/ketchup/src/components/ketchup-data-table/ketchup-data-table.tsx, packages/ketchup/src/utils/object-utils.ts, packages/ketchup/tests/e2e/data-table/data-table-grouping.e2e.ts
* code refactoring
* show grid disabled by default
* url cell
* fix e2e tests
=> Data table: code refactoring and new features

packages/ketchup-showcase/package-lock.json, packages/ketchup/package-lock.json, packages/ketchup/package.json, packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-gauge/kup-gauge.scss, packages/ketchup/src/components/kup-gauge/kup-gauge.tsx, packages/ketchup/src/components/kup-gauge/readme.md, packages/ketchup/src/index.html
First version of the kup-gauge component. Missing showcase and tests, which will be added later.
=> kup-gauge@1.0

packages/ketchup-showcase/src/mock/dataTable.ts, packages/ketchup/src/components/kup-data-table/kup-data-table-declarations.ts, packages/ketchup/src/components/kup-data-table/kup-data-table-helper.ts, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/components/kup-paginator/readme.md, packages/ketchup/src/components/kup-text-input/readme.md, packages/ketchup/tests/e2e/data-table/data-table-basic.e2e.ts, packages/ketchup/tests/e2e/data-table/data-table-grouping.e2e.ts, packages/ketchup/tests/e2e/data-table/data-table-sort.e2e.ts, packages/ketchup/tests/e2e/data-table/mocked-data.ts, packages/ketchup/tests/unit/data-table/data-table-grouping.spec.ts
- Fix sort on invalid column
- Fix grouping on invalid column
- Sort on group rows, if none is defined
- Style with borderRadius: apply to cell-content instead of td
=> Kup data table corrections

packages/ketchup-showcase/src/components/HelloWorld.vue
=> HelloWorld comp

packages/ketchup/src/components/kup-dash/kup-dash.scss, packages/ketchup/src/components/kup-gauge/kup-gauge.scss, packages/ketchup/src/components/kup-gauge/kup-gauge.tsx
Removed min-height from Dash.
Three colors in variables for Gauge.
=> Fix dash and gauge variables

packages/ketchup-showcase/src/App.vue, packages/ketchup-showcase/src/plugins/router/box.ts, packages/ketchup-showcase/src/views/box/BoxClasses.vue, packages/ketchup-showcase/src/views/box/BoxLayout.vue, packages/ketchup-showcase/src/views/box/BoxSel.vue, packages/ketchup/package-lock.json, packages/ketchup/package.json, packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-box/kup-box-declarations.ts, packages/ketchup/src/components/kup-box/kup-box.scss, packages/ketchup/src/components/kup-box/kup-box.tsx, packages/ketchup/src/components/kup-box/readme.md, packages/ketchup/tests/e2e/box/box-basic.e2e.ts, packages/ketchup/tests/e2e/box/box-layout.e2e.ts, packages/ketchup/tests/e2e/box/box-selection.e2e.ts, packages/ketchup/tests/e2e/data-table/data-table-actions.e2e.ts, packages/ketchup/tests/e2e/data-table/data-table-basic.e2e.ts, packages/ketchup/tests/e2e/data-table/data-table-grouping.e2e.ts, packages/ketchup/tests/e2e/data-table/data-table-sort.e2e.ts
- Sections with column
- Sections with title
- no-shadow css class
- selectBox prop
- showSelection prop
- e2e test refactoring
=> Box new features / e2e test refactoring

packages/ketchup-showcase/src/App.vue, packages/ketchup-showcase/src/plugins/router/box.ts, packages/ketchup-showcase/src/views/box/BoxClasses.vue, packages/ketchup-showcase/src/views/box/BoxLayout.vue, packages/ketchup-showcase/src/views/box/BoxSel.vue, packages/ketchup/package-lock.json, packages/ketchup/package.json, packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-box/kup-box-declarations.ts, packages/ketchup/src/components/kup-box/kup-box.scss, packages/ketchup/src/components/kup-box/kup-box.tsx, packages/ketchup/src/components/kup-box/readme.md, packages/ketchup/src/components/kup-text-input/kup-text-input.scss, packages/ketchup/src/components/kup-text-input/kup-text-input.tsx, packages/ketchup/tests/e2e/box/box-basic.e2e.ts, packages/ketchup/tests/e2e/box/box-layout.e2e.ts, packages/ketchup/tests/e2e/box/box-selection.e2e.ts, packages/ketchup/tests/e2e/data-table/data-table-actions.e2e.ts, packages/ketchup/tests/e2e/data-table/data-table-basic.e2e.ts, packages/ketchup/tests/e2e/data-table/data-table-grouping.e2e.ts, packages/ketchup/tests/e2e/data-table/data-table-sort.e2e.ts
Merge this pr first: [PR](https://github.com/smeup/ketchup/pull/70)
Added a flex container to easily align items.
=> Itx refactoring

packages/ketchup/src/components/kup-portal/kup-portal.tsx
Fixed a regression error for the portal receiving some data one step later before its current usage.
=> Regression: fixed how portal sets data onto the portal instance.

packages/ketchup/src/components/kup-data-table/kup-data-table.scss, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/components/kup-paginator/kup-paginator.scss
- FIxed issue on paginator icons' size.
- Added variable for paginator icons' text color.
=> Changes to paginator

packages/ketchup/src/components/kup-data-table/kup-data-table.scss, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/utils/scroll-on-hover.ts
- Fixed scroll on hover, now it works even when there is a different offset on the parent container.
- Fixed sticky header for row-actions and selections
=> Fix for sticky header and scroll on hover

packages/ketchup/src/utils/scroll-on-hover.ts
=> Possible fix for scroll on hover

packages/ketchup/src/components/kup-badge/readme.md, packages/ketchup/src/components/kup-box/readme.md, packages/ketchup/src/components/kup-btn/readme.md, packages/ketchup/src/components/kup-button/readme.md, packages/ketchup/src/components/kup-calendar/readme.md, packages/ketchup/src/components/kup-checkbox/readme.md, packages/ketchup/src/components/kup-chip/kup-chip.scss, packages/ketchup/src/components/kup-chip/readme.md, packages/ketchup/src/components/kup-combo/readme.md, packages/ketchup/src/components/kup-data-table/readme.md, packages/ketchup/src/components/kup-fld/readme.md, packages/ketchup/src/components/kup-graphic-cell/readme.md, packages/ketchup/src/components/kup-html/readme.md, packages/ketchup/src/components/kup-image/readme.md, packages/ketchup/src/components/kup-paginator/readme.md, packages/ketchup/src/components/kup-portal-instance/readme.md, packages/ketchup/src/components/kup-portal/readme.md, packages/ketchup/src/components/kup-progress-bar/readme.md, packages/ketchup/src/components/kup-radio-element/readme.md, packages/ketchup/src/components/kup-text-input/readme.md, packages/ketchup/src/components/kup-tooltip/readme.md, packages/ketchup/src/components/kup-tree/readme.md
- Removed left margin to improve alignment.
=> Changed margin left for chips

packages/ketchup-showcase/src/views/box/BoxClasses.vue, packages/ketchup/src/components/kup-box/kup-box.scss, packages/ketchup/src/components/kup-box/kup-box.tsx
Inverted with-padding class on box and set center-aligned as section default
=> Box CSS changes

packages/ketchup-showcase/src/mock/dataTable.ts
=> Revert "Update dataTable.ts"

packages/ketchup-showcase/src/mock/dataTable.ts
=> Revert "Revert "Update dataTable.ts""

packages/ketchup/src/components/kup-chart-cell/kup-chart-cell-declarations.ts
a quello presente nella versione JSF
=> impostati default dimensionamento charts uguale

packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-checkbox/kup-checkbox.scss, packages/ketchup/src/components/wup-button/readme.md, packages/ketchup/src/components/wup-button/wup-button.scss, packages/ketchup/src/components/wup-button/wup-button.tsx, packages/ketchup/src/components/wup-checkbox/readme.md, packages/ketchup/src/components/wup-checkbox/wup-checkbox.scss, packages/ketchup/src/components/wup-checkbox/wup-checkbox.tsx, packages/ketchup/src/components/wup-radio/readme.md, packages/ketchup/src/components/wup-radio/wup-radio.scss, packages/ketchup/src/components/wup-radio/wup-radio.tsx, packages/ketchup/src/components/wup-switch/readme.md, packages/ketchup/src/components/wup-switch/wup-switch.scss, packages/ketchup/src/components/wup-switch/wup-switch.tsx, packages/ketchup/src/components/wup-tab-bar/readme.md, packages/ketchup/src/components/wup-tab-bar/wup-tab-bar.scss, packages/ketchup/src/components/wup-tab-bar/wup-tab-bar.tsx, packages/ketchup/src/components/wup-template/readme.md, packages/ketchup/src/components/wup-template/wup-template.scss, packages/ketchup/src/components/wup-template/wup-template.tsx, packages/ketchup/src/components/wup-text-field/readme.md, packages/ketchup/src/components/wup-text-field/wup-text-field.scss, packages/ketchup/src/components/wup-text-field/wup-text-field.tsx, packages/ketchup/src/style/_variables.scss
- Refactoring widgets to follow Template guidelines. 
- Reduced density for text fields and tab bar.
=> Widgets template

packages/ketchup-showcase/public/showcase.css, packages/ketchup-showcase/public/showcase.js, packages/ketchup-showcase/src/views/Theming.vue, packages/ketchup-showcase/src/views/basic/button/examples/ButtonBasic.vue, packages/ketchup/src/components.d.ts, packages/ketchup/src/components/wup-button/readme.md, packages/ketchup/src/components/wup-button/wup-button.scss, packages/ketchup/src/components/wup-button/wup-button.tsx, packages/ketchup/src/components/wup-checkbox/readme.md, packages/ketchup/src/components/wup-checkbox/wup-checkbox.tsx, packages/ketchup/src/components/wup-radio/readme.md, packages/ketchup/src/components/wup-radio/wup-radio.tsx, packages/ketchup/src/components/wup-switch/readme.md, packages/ketchup/src/components/wup-switch/wup-switch.tsx, packages/ketchup/src/components/wup-tab-bar/readme.md, packages/ketchup/src/components/wup-tab-bar/wup-tab-bar.tsx, packages/ketchup/src/components/wup-template/readme.md, packages/ketchup/src/components/wup-template/wup-template.tsx, packages/ketchup/src/components/wup-text-field/readme.md, packages/ketchup/src/components/wup-text-field/wup-text-field.tsx, packages/ketchup/src/index.html
- Fixed JS problems on checkNav method, 
- Changed theming page to let text field trigger the value override on input
- Adjusted padding for no-nav pages.
- Refactoring events, now they handle values more consistently. 
- New Demo panel in button basic component. 
- Remove custom class from components.
=> Small refactoring on basic components events, new demo panel

packages/ketchup/src/components/wup-button/wup-button.tsx
=> Fix event on button.

packages/ketchup-showcase/public/showcase.css, packages/ketchup-showcase/src/views/Theming.vue, packages/ketchup-showcase/src/views/basic/button/examples/ButtonBasic.vue, packages/ketchup-showcase/src/views/basic/button/examples/ButtonDisabled.vue, packages/ketchup-showcase/src/views/basic/button/examples/ButtonIconVariant.vue, packages/ketchup-showcase/src/views/basic/button/examples/ButtonStyling.vue, packages/ketchup-showcase/src/views/basic/textfield/examples/TextfieldStyling.vue, packages/ketchup/src/components.d.ts, packages/ketchup/src/components/wup-button/readme.md, packages/ketchup/src/components/wup-button/wup-button.tsx, packages/ketchup/src/components/wup-checkbox/wup-checkbox.tsx, packages/ketchup/src/components/wup-radio/wup-radio.tsx, packages/ketchup/src/components/wup-switch/wup-switch.tsx, packages/ketchup/src/components/wup-tab-bar/wup-tab-bar.tsx, packages/ketchup/src/components/wup-template/wup-template.tsx, packages/ketchup/src/components/wup-text-field/readme.md, packages/ketchup/src/components/wup-text-field/wup-text-field.scss, packages/ketchup/src/components/wup-text-field/wup-text-field.tsx, packages/ketchup/src/index.html
- Added transition to demo panels.
- Added new prop to text field, fullheight. Used fullheight text fields in demo panel and theming page.
- Added transition to <html>.
- Small refactoring in basic components to change variables names (and showcase accordingly)
=> Read comments.

packages/ketchup-showcase/src/mock/tooltip.ts, packages/ketchup-showcase/src/views/advanced/tooltip/examples/TooltipBasic.vue, packages/ketchup/src/components/kup-tooltip/kup-tooltip-declarations.ts, packages/ketchup/src/components/kup-tooltip/kup-tooltip.scss, packages/ketchup/src/components/kup-tooltip/kup-tooltip.tsx
Inserita una actionbar nella parte inferiore del tooltip
=> Pd000152 tooltip actionbar

packages/ketchup/src/components/kup-tooltip/kup-tooltip-declarations.ts, packages/ketchup/src/components/kup-tooltip/kup-tooltip.tsx
Stopped click propation, doubled opening timeout, solved issues with 
popup blocker.
=> Minor changes and fix

packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-text-field/kup-text-field.tsx, packages/ketchup/src/components/kup-text-field/readme.md
Also, emitted id in all text field events.
=> Hotfix for emission of text field clear event.

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx
=> added hide column action

packages/ketchup-showcase/src/views/advanced/chart/examples/ChartDemo.vue, packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-chart/kup-chart.tsx, packages/ketchup/src/components/kup-chart/readme.md
=> Improved chart legend, adding more possibilities.

packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-drawer/kup-drawer.css, packages/ketchup/src/components/kup-drawer/kup-drawer.tsx, packages/ketchup/src/components/kup-drawer/readme.md, packages/ketchup/src/components/kup-drawer/test/kup-drawer.e2e.ts, packages/ketchup/src/components/kup-drawer/test/kup-drawer.spec.tsx, packages/ketchup/src/drawer.html, packages/ketchup/src/index.html
=> Kup drawer

packages/ketchup/src/components/kup-box/kup-box.tsx, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/components/kup-tree/kup-tree.scss, packages/ketchup/src/components/kup-tree/kup-tree.tsx, packages/ketchup/src/style/_generic-style.scss
=> Added "is-obj" class to tree box and data table, changed cursor to "alias" when present.

packages/ketchup/src/assets/data-table.js, packages/ketchup/src/components/kup-data-table/kup-data-table-helper.ts, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/data-table.html
fix order by groups in tables: it didn't work if there are some blank values to order
=> Kup data table fix order grouped rows

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx
=> Fixed gauge, rating, color picker, chips cells (were handled like non-component cells).

packages/ketchup/src/components/kup-chart/kup-chart.spec.ts, packages/ketchup/src/components/kup-chart/kup-chart.tsx
kup-chart: view series decode in legend (not code) - fix compilation problem
=> Fix ketchup charts

README.md
=> Update README.md: Changed payoff

packages/ketchup/src/components/kup-field/kup-field.tsx
=> Fixed kup-field change event when text field.

packages/ketchup/src/components/kup-tree/kup-tree.scss
=> Fixed selected color on tree nodes.

packages/ketchup/src/components/kup-gauge/kup-gauge.scss, packages/ketchup/src/components/kup-gauge/kup-gauge.tsx, packages/ketchup/src/index.html
=> kup-gauge responsive

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx
=> Data table: obj related title displayed only in debug mode.

packages/ketchup-showcase/public/showcase.css, packages/ketchup-showcase/src/App.vue
=> Showcase: wrapped "basic" and "advanced" under "components" inside drawer

packages/ketchup-showcase/src/views/basic/colorpicker/examples/ColorPickerDemo.vue, packages/ketchup/package-lock.json, packages/ketchup/package.json, packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-color-picker/kup-color-picker.scss, packages/ketchup/src/components/kup-color-picker/kup-color-picker.tsx, packages/ketchup/src/components/kup-color-picker/readme.md, packages/ketchup/src/components/kup-crud/readme.md, packages/ketchup/src/components/kup-data-table/readme.md, packages/ketchup/src/components/kup-form/readme.md, packages/ketchup/src/components/kup-search/readme.md, packages/ketchup/src/components/kup-text-field/readme.md
=> Color picker dropdown

packages/ketchup-showcase/src/mock/dataTable.ts, packages/ketchup-showcase/src/views/advanced/datatable/examples/DatatableRowActions.vue, packages/ketchup/src/assets/data-table.js, packages/ketchup/src/components/kup-data-table/kup-data-table-declarations.ts, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx
kup-data-table: managed prop title for cell (simple tooltip), onClick on row action don't select the row
=> Kup data table small issue

packages/ketchup-showcase/src/views/advanced/datatable/examples/DatatableDemo.vue, packages/ketchup-showcase/src/views/advanced/tree/examples/TreeDemo.vue, packages/ketchup/src/components/kup-data-table/modules/kup-data-table-classes.scss, packages/ketchup/src/components/kup-tree/modules/kup-tree-classes.scss
=> layout-fixed class on tree.

packages/ketchup-showcase/src/views/css/theming/examples/ThemingMaker.vue, packages/ketchup/src/components/kup-autocomplete/kup-autocomplete.scss, packages/ketchup/src/components/kup-autocomplete/kup-autocomplete.tsx, packages/ketchup/src/components/kup-color-picker/kup-color-picker.scss, packages/ketchup/src/components/kup-color-picker/kup-color-picker.tsx, packages/ketchup/src/components/kup-combobox/kup-combobox.scss, packages/ketchup/src/components/kup-combobox/kup-combobox.tsx, packages/ketchup/src/components/kup-date-picker/kup-date-picker.scss, packages/ketchup/src/components/kup-date-picker/kup-date-picker.tsx, packages/ketchup/src/components/kup-text-field/kup-text-field.scss, packages/ketchup/src/components/kup-time-picker/kup-time-picker.scss, packages/ketchup/src/components/kup-time-picker/kup-time-picker.tsx, packages/ketchup/src/utils/theme-manager.ts
=> Theme maker adjustments

packages/ketchup/src/components/kup-box/kup-box.tsx, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/components/kup-list/kup-list-declarations.ts, packages/ketchup/src/components/kup-tree/kup-tree.tsx, packages/ketchup/src/components/kup-tree/modules/kup-tree-main.scss
=> Global filter delay

packages/ketchup/src/components/kup-checkbox/kup-checkbox.tsx
=> kup-checkbox: select/deselect checkbox onClick on label

packages/ketchup/src/components/kup-tree/kup-tree.tsx, packages/ketchup/src/tree.html
kup-tree: managed layout fixed and set column size, for trees with more than 2000 children
=> kup-tree: managed layout fixed and set column size

packages/ketchup/src/components/kup-tree/kup-tree.tsx
=> Layout fixed tre

packages/ketchup/src/assets/data-table.js, packages/ketchup/src/components/kup-data-table/kup-data-table-declarations.ts, packages/ketchup/src/components/kup-data-table/kup-data-table-helper.ts, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/data-table.html
kup-data-table: server side creation of filter options (checkboxes) list for column
Closes #729
=> kup-data-table: server side creation of filter options (checkboxes)

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/components/kup-data-table/modules/kup-data-table-main.scss
=> Replaced kup-image with embedded code inside data table for css type 'bar' and 'icon'/'image' cells.

packages/ketchup-showcase/package.json, packages/ketchup/package.json
da effettuare dopo l'apporvazione della PR su release
=> Develop up version

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/components/kup-data-table/modules/kup-data-table-main.scss
=> Removed kup-checkbox from obj cells, replaced with static icons.

packages/ketchup/src/components/kup-button/kup-button.scss, packages/ketchup/src/components/kup-dropdown-button/kup-dropdown-button.scss, packages/ketchup/src/components/kup-dropdown-button/kup-dropdown-button.tsx, packages/ketchup/src/utils/recalc-position.ts
=> Recalc position fix

packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/components/kup-data-table/modules/kup-data-table-main.scss, packages/ketchup/src/components/kup-data-table/readme.md, packages/ketchup/src/utils/object-utils.ts
create overlay event, attached to column in kup-data-table (used in webUp for add decode column)
=> Add automatic decode column

packages/ketchup/src/utils/utils.ts, packages/ketchup/tests/e2e/data-table/data-table-hide-repetitions.e2e.ts
format decimal numbers without round value, if no decimals number value (for output) set
=> format decimal numbers without round value

packages/ketchup-showcase/src/mock/dataTable.ts, packages/ketchup-showcase/src/views/advanced/datatable/examples/DatatableDateTimeNumberCell.vue, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/components/kup-date-picker/kup-date-picker.tsx, packages/ketchup/src/utils/utils.ts, packages/ketchup/tests/e2e/data-table/data-table-grouping.e2e.ts
format dates by user locale (without using info in smeupObject) in kup-data-table; fix manage dates in kup-date-picker
=> format dates by user locale (without using info in smeupObject) 

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/components/kup-date-picker/kup-date-picker.tsx, packages/ketchup/src/utils/utils.ts, packages/ketchup/tests/e2e/data-table/data-table-grouping.e2e.ts
put on master branch the fixes of develop, for manageing date columns in data table, anche filters on dates
=> put on master branch the fixes of develop, for manageing date columns

packages/ketchup/src/components/kup-data-table/kup-data-table.scss, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/f-components/f-checkbox/f-checkbox.tsx, packages/ketchup/src/f-components/f-chip/f-chip.tsx, packages/ketchup/src/f-components/f-image/f-image.tsx, packages/ketchup/src/f-components/f-switch/f-switch.tsx, packages/ketchup/src/f-components/f-text-field/f-text-field.tsx
=> Row selection: now selection works only by interacting with row checkboxes (replaced kup-checkbox with f-checkbox).

packages/ketchup/src/assets/data-table.js, packages/ketchup/src/components/kup-data-table/kup-data-table-helper.ts, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/data-table.html, packages/ketchup/src/utils/utils.ts
kup-data-table: fix filter on numeric columns; fix filter on hidden columns; fix reg.expr. filter on numeric columns
=> kup-data-table: fix filters 

packages/ketchup/src/components/kup-data-table/kup-data-table-helper.ts
kup-data-table: fix grouping and sort grouped rows on date type column (master)
=> kup-data-table: fix grouping and sort grouped rows on date (master)

packages/ketchup/src/components/kup-data-table/kup-data-table-helper.ts, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx
=> Fixed js error inside evaluateFormula and fixed hover effect on mouse out.

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/components/kup-tooltip/kup-tooltip.scss
Needs further testing on Webup Ketchup.
=> Removed click event listener to document which caused bugs with blur.

packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-box/kup-box.tsx, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/components/kup-tooltip/kup-tooltip-declarations.ts, packages/ketchup/src/components/kup-tooltip/kup-tooltip.tsx, packages/ketchup/src/components/kup-tooltip/readme.md, packages/ketchup/src/components/kup-tree/kup-tree.tsx, packages/ketchup/src/utils/helpers.ts
managed tooltip owner prop anche send rowId from owner component that opened the tip
=> managed tooltip owner prop anche send rowId from owner component (develop)

packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-box/kup-box.tsx, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/components/kup-tooltip/kup-tooltip-declarations.ts, packages/ketchup/src/components/kup-tooltip/kup-tooltip.tsx, packages/ketchup/src/components/kup-tooltip/readme.md, packages/ketchup/src/components/kup-tree/kup-tree.tsx, packages/ketchup/src/utils/helpers.ts
managed tooltip owner prop anche send rowId from owner component that opened the tip
=> managed tooltip owner prop anche send rowId from owner component (release)

packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-btn/kup-btn-declarations.ts, packages/ketchup/src/components/kup-btn/kup-btn.tsx, packages/ketchup/src/components/kup-btn/readme.md, packages/ketchup/src/components/kup-btn/styles/kup-btn-main.scss, packages/ketchup/src/utils/kup-column-menu/kup-column-menu.ts
=> Kup btn show selection

packages/ketchup/src/components/kup-autocomplete/readme.md, packages/ketchup/src/components/kup-badge/readme.md, packages/ketchup/src/components/kup-box/readme.md, packages/ketchup/src/components/kup-card/readme.md, packages/ketchup/src/components/kup-crud/readme.md, packages/ketchup/src/components/kup-data-table/kup-data-table-declarations.ts, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/components/kup-data-table/readme.md, packages/ketchup/src/components/kup-data-table/styles/kup-data-table-drag-drop.scss, packages/ketchup/src/components/kup-fab/readme.md, packages/ketchup/src/components/kup-form/readme.md, packages/ketchup/src/components/kup-magic-box/readme.md, packages/ketchup/src/components/kup-search/readme.md, packages/ketchup/src/components/kup-tooltip/readme.md, packages/ketchup/src/components/kup-tree/readme.md
todo: to clean source, after fix a problem on NOT draggable column after remove all groups for data-table
=> added automatic grouping by column, dragging the column header on the appropriate drop area

packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/components/kup-data-table/readme.md
…rce component (compilation error)
=> kup-data-table: kupAddCodeDecodeColumn event: removed for now the source component (compilation error)

packages/ketchup-showcase/public/showcase.css, packages/ketchup-showcase/src/views/advanced/accordion/examples/AccordionDemo.vue, packages/ketchup-showcase/src/views/advanced/page/templates/Demo.vue, packages/ketchup-showcase/src/views/basic/chip/examples/ChipDemo.vue, packages/ketchup-showcase/src/views/basic/gauge/examples/GaugeDemo.vue, packages/ketchup-showcase/src/views/basic/image/examples/ImageDemo.vue, packages/ketchup-showcase/src/views/basic/list/examples/ListDemo.vue, packages/ketchup-showcase/src/views/basic/navbar/examples/NavbarDemo.vue, packages/ketchup-showcase/src/views/basic/radio/examples/RadioDemo.vue, packages/ketchup-showcase/src/views/basic/tabbar/examples/TabbarDemo.vue
=> Playground tooltip: first step (basic components)

packages/ketchup/src/components/kup-card/standard/kup-card-standard.tsx
Added group button in layout 14 and removed the switch group from settings of layout 14
=> kup-card: Added group button in layout 14

packages/ketchup-showcase/src/views/advanced/datatable/Datatable.vue, packages/ketchup-showcase/src/views/advanced/datatable/examples/DatatableDemo.vue, packages/ketchup-showcase/src/views/advanced/datatable/examples/DatatableFormula.vue, packages/ketchup-showcase/src/views/advanced/datatable/examples/DatatableMerge.vue, packages/ketchup-showcase/src/views/basic/lazy/examples/LazyDemo.vue, packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-box/readme.md, packages/ketchup/src/components/kup-card/kup-card.tsx, packages/ketchup/src/components/kup-card/readme.md, packages/ketchup/src/components/kup-cell/readme.md, packages/ketchup/src/components/kup-data-table/kup-data-table-declarations.ts, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/components/kup-data-table/readme.md, packages/ketchup/src/components/kup-date-picker/readme.md, packages/ketchup/src/components/kup-dropdown-button/readme.md, packages/ketchup/src/components/kup-lazy/kup-lazy.tsx, packages/ketchup/src/components/kup-lazy/readme.md, packages/ketchup/src/components/kup-magic-box/readme.md, packages/ketchup/src/components/kup-time-picker/readme.md, packages/ketchup/src/components/kup-tooltip/readme.md, packages/ketchup/src/components/kup-tree/readme.md, packages/ketchup/src/utils/kup-objects/kup-objects.ts
Created public method to merge 2 or n columns.
=> kup-data-table

packages/ketchup/src/components/kup-echart/kup-echart.tsx, packages/ketchup/src/managers/kup-data/kup-data-cell-helper.ts, packages/ketchup/src/managers/kup-data/kup-data.ts, packages/ketchup/src/utils/filters/filters-rows.ts, packages/ketchup/src/utils/filters/filters-tree-items.ts
- KupEchartTypes.GAUSSIAN: safe managing if axis are missing; fixed values trasformation for passing to graph
- KupEchartTypes.BAR (+ KupEchartTypes.GAUSSIAN): fix extract values for bars
=> kup-echart: fixes managing data

packages/ketchup/src/components/kup-button/styles/kup-button-main.scss, packages/ketchup/src/f-components/f-button/f-button.scss
expose style variable to easily set the text transform (uppercase is the default)
=> f-button: add new variable for text transform

packages/ketchup/src/drawer.html
=> drawer: bugfix on example

packages/ketchup-showcase/Dockerfile, packages/ketchup-showcase/vue.config.js
Add missing public path for ketchup-showcase
=> Fix application public path

packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-planner/kup-planner-declarations.ts, packages/ketchup/src/components/kup-planner/kup-planner.tsx
Props added:
- listCellWidth (default 300px)
- showSecondaryDates (default false)
=> Styling and formatting date fixes, and added new props

.github/workflows/develop-release.yml
Add github action for CI/CD installazione webup con branch ketchup su smartkit v2
=> Staging cicd

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/scripts/postCreateCommand.sh, .github/dependabot.yml
=> chore: setup devcontainer

packages/ketchup-react/src/index.ts, packages/ketchup/src/assets/index.js, packages/ketchup/src/assets/input-panel.js, packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-card/readme.md, packages/ketchup/src/components/kup-dialog/readme.md, packages/ketchup/src/components/kup-input-panel/kup-input-panel-declarations.ts, packages/ketchup/src/components/kup-input-panel/kup-input-panel.scss, packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx, packages/ketchup/src/components/kup-input-panel/readme.md, packages/ketchup/src/input-panel.html, packages/ketchup/src/managers/kup-theme/kup-theme-declarations.ts, packages/ketchup/src/types/GenericTypes.ts, packages/ketchup/stencil.config.ts
PR for testing deployment on staging.
=> Inputpanel - preview only

packages/ketchup/src/f-components/f-image/f-image.tsx
Remove kup fit for icons problems
=> Remove kup-fit

packages/ketchup/src/assets/box.js, packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-pdf/readme.md, packages/ketchup/src/f-components/f-cell/f-cell.scss, packages/ketchup/src/f-components/f-cell/f-cell.tsx
Icon and image management for F-cell imageshape cell due to webup icon/image new management
=> Icon-cell image/icon management 

packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx
=> feat(kup-input-panel): added datatable defaults for groups, filters and footer

packages/ketchup/src/components/kup-card/built-in/kup-card-built-in-1.scss, packages/ketchup/src/components/kup-card/built-in/kup-card-calendar.tsx, packages/ketchup/src/components/kup-date-picker/kup-date-picker.tsx, packages/ketchup/src/managers/kup-dates/kup-dates.ts, yarn.lock
- adding validations on datepicker
=> Kup date picker

packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-card/built-in/kup-card-built-in-1.scss, packages/ketchup/src/components/kup-date-picker/kup-date-picker-declarations.tsx, packages/ketchup/src/components/kup-date-picker/kup-date-picker.tsx, packages/ketchup/src/date-picker.html, packages/ketchup/src/f-components/f-text-field/f-text-field.scss
- max-width card calendar
- Outlined border
- extra-small management
=> feat/add date-picker functionalities

packages/ketchup-showcase/src/mock/dataTable.ts, packages/ketchup-showcase/src/views/components/advanced/datatable/examples/DatatableRowActions.vue, packages/ketchup-showcase/src/views/components/advanced/datatable/examples/DatatableRowActionsWithCommands.vue, packages/ketchup/src/components/kup-card/standard/kup-card-standard-17.scss, packages/ketchup/src/components/kup-card/standard/kup-card-standard.tsx, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx
If there are < than 10 elements, filter will not appear.
Otherwise, it will be shown
=> Datatable: filter in actions dropdown

packages/ketchup/src/managers/kup-data/kup-data.ts
fixes a missed control on row Actions
=> fix: control on row action

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx
=> fix: changed emit event with new

packages/ketchup-showcase/src/mock/dataTable.ts, packages/ketchup/src/managers/kup-data/kup-data.ts, packages/ketchup/tests/unit/components/kup-data-table/kup-data-table-row-actions.spec.ts
- fixed examples on vue showcase and behavior of title to show when there is no commands corresponding
=> fix showcase examples

packages/ketchup/src/components/kup-data-table/styles/kup-data-table-main.scss
=> feat / kup-data-table / cell size

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/managers/kup-data/kup-data.ts, packages/ketchup/tests/unit/components/kup-data-table/kup-data-table-row-actions.spec.ts
- fix applied for actions without text. When there is a correspondence with commands that have no text, action will be showed with title of the column or, if missing, name of the column
=> Fix - Row actions text 

packages/ketchup/src/assets/image-list.js, packages/ketchup/src/components/kup-image-list/kup-image-list.tsx
Changed columns prop array type to number[ ]. Prop initialized as [ ]
=> Fix/image list/changed columns from KupDataNode to number

packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-image-list/kup-image-list.tsx
Removed the forced default values (used in case of empty columns array) because they overwrite the default media query ones
=> fix / image-list / removed forced default

packages/ketchup/src/f-components/f-cell/f-cell.scss
manage the padding value for the fcell input-field padding.
=> fix / fcell

packages/ketchup/src/components/kup-input-panel/kup-input-panel.e2e.ts
Implemented 3 types of e2e test:
- check tabs existence when sectionType value is 'tab'
- check for data attribute error
- check position absolute when absolute property is true
=> Implemented e2e test for input panel component

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/components/kup-data-table/styles/kup-data-table-main.scss
fix data-table overflow with specified height and width on 100%
=> fix / fixed table overflow

packages/ketchup/src/f-components/f-text-field/f-text-field.scss, packages/ketchup/src/style/fonts.scss
- correct variables name
- insert variable font size
=> feat / font size and default

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx
- fixed bug that does not make J4;ICO objects not clickable inside datatable
=> fix: cell action regression

packages/ketchup/src/components/kup-data-table/kup-data-table-helper.ts, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx
The decorating function in this implementation add the props to the cells to handle this graphic shapes:
- Autocomplete
- Combobox
- Radio
- Checkbox
- Chip
=> Introduced a decoration function when SmeupDataTable is the JSON data type passed to kup-data-table

packages/ketchup/src/components/kup-button-list/kup-button-list.tsx, packages/ketchup/src/f-components/f-button/f-button.scss, packages/ketchup/src/f-components/f-button/f-button.tsx, packages/ketchup/src/managers/kup-theme/themes.json
- Added flat case
- Manage kup-list default
=> feat / f-button / manage flat variable and list deafult

packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx
- moved code that was useless in the previous position
=> fix: horizontal maxWidth/Height for input panel

packages/ketchup/src/assets/radio.js, packages/ketchup/src/f-components/f-radio/f-radio-declarations.ts, packages/ketchup/src/f-components/f-radio/f-radio.scss, packages/ketchup/src/f-components/f-radio/f-radio.tsx, packages/ketchup/src/managers/kup-theme/kup-theme-declarations.ts, packages/ketchup/src/radio.html, packages/ketchup/tsconfig.json
create a new radio type re-using the logic of the existing f-radio as it behave in the same way.
The new radio type can be named Chevron as 'check' cannot be used.
=> feat / new radio type

packages/ketchup/src/f-components/f-cell-options.tsx/f-cell-options.tsx
Added generation for columns and rows. Also, adapter for shape ITX has been updated
=> Fix for f-cell-options

packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx
fix horizontal layout input panel
=> bugfix(kup-input-panel): handled horizontal layout

packages/ketchup/src/components/kup-cell/kup-cell.tsx, packages/ketchup/src/f-components/f-cell-options.tsx/f-cell-options.tsx, packages/ketchup/src/f-components/f-cell/f-cell-declarations.ts, packages/ketchup/src/f-components/f-cell/f-cell.tsx, packages/ketchup/src/managers/kup-data/kup-data-declarations.ts
Moved RAD adapter from f-cell-options to f-cell
=> Moving f-cell-options RAD adapter in f-cell

packages/ketchup/src/components/kup-cell/kup-cell.tsx, packages/ketchup/src/f-components/f-cell-options.tsx/f-cell-options.tsx, packages/ketchup/src/f-components/f-cell/f-cell.tsx
Moved ACP adapter from f-cell-options to f-cell
=> Moving f-cell-options ACP adapter in f-cell

packages/ketchup/src/f-components/f-cell-options.tsx/f-cell-options.tsx, packages/ketchup/src/f-components/f-cell/f-cell.tsx
Moved CMB adapter from f-cell-options to f-cell
=> Moving f-cell-options CMB adapter in f-cell 

packages/ketchup/src/f-components/f-cell-options.tsx/f-cell-options.tsx, packages/ketchup/src/f-components/f-cell/f-cell.tsx
Moved BTN adapter from f-cell-options to f-cell
=> Moving f-cell-options BTN adapter in f-cell 

packages/ketchup/src/f-components/f-cell-options.tsx/f-cell-options.tsx, packages/ketchup/src/f-components/f-cell/f-cell.tsx
Moved ITX adapter from f-cell-options to f-cell
=> Moving f-cell-options ITX adapter in f-cell 

packages/ketchup/src/f-components/f-cell/f-cell.tsx
Integrated OBJ and CHK shapes in Fcell
=> Fcell adapters for OBJ and CHK shapes

packages/ketchup/src/components/kup-input-panel/kup-input-panel.scss
=> tmp: fix height in absolute layout input-panel

packages/ketchup/src/f-components/f-cell/f-cell.tsx
- Fixed chip adapter variable assignment
=> CHI adapter fix

packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx
Fixed a problem where dim inside property layout was not considered
=> Fix layout input panel problem: missing dim on sections

packages/ketchup/src/assets/input-panel.js, packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx
Do not show label inside input panel pos abs.
=> feat / no label inside comp in pos abs

packages/ketchup/src/f-components/f-cell/f-cell.scss
Set Max-width property for fcell
=> FCell max-width

packages/ketchup/src/assets/toolbar.js, packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-card/readme.md, packages/ketchup/src/components/kup-dialog/readme.md, packages/ketchup/src/components/kup-dropdown-button/readme.md, packages/ketchup/src/components/kup-input-panel/readme.md, packages/ketchup/src/components/kup-toolbar/kup-toolbar-declarations.ts, packages/ketchup/src/components/kup-toolbar/kup-toolbar.scss, packages/ketchup/src/components/kup-toolbar/kup-toolbar.tsx, packages/ketchup/src/components/kup-toolbar/readme.md
It needs to be accepted at the same time as the Webup.js PR on collapse/expand node
=> feat / update toolbar management

packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-image-list/readme.md, packages/ketchup/src/components/kup-switch/readme.md, packages/ketchup/src/f-components/f-button/f-button.tsx
=> feat / small default buttons

packages/ketchup/src/f-components/f-checkbox/f-checkbox.scss
Fixed a problem in checkbox alignment when clicking in box
=> fix: width & height in f-checkbox

packages/ketchup/src/f-components/f-cell/f-cell.scss
removed class css in f-cell in contrast with f-checkbox
=> f-cell checkbox css class

packages/ketchup/src/assets/echart.js, packages/ketchup/src/components/kup-echart/kup-echart.tsx
Solves problems in a couple graph forms. 
More precisely, solves problems in graphs with highest priority:
- Line 
- HBar Single and Multiple series
- VBar Single and Multiple series
- Pie 2D only ( as far as i know, 3D version was not implemented in `kup-echart`, am I right?)
- Scatter
- Bubble
- Sankey
Line and Pie charts were not present in Working Sch, so I checked their behavior in showcase.
This PR also carries some initial development by @andraasi , split in these PRs:
#closes https://github.com/smeup/ketchup/pull/2176
#closes https://github.com/smeup/ketchup/pull/2175
#closes https://github.com/smeup/ketchup/pull/2174
=> fix: various graph forms

packages/ketchup/src/f-components/f-text-field/f-text-field.scss, packages/ketchup/src/f-components/f-text-field/f-text-field.tsx
manage text-area css
set textarea true whenever maxLength is more than 256 char
=> feat / textfield / text-area

packages/ketchup/src/f-components/f-cell/f-cell.tsx, packages/ketchup/src/managers/kup-data/kup-data-declarations.ts
Added props when textfield is of number type
=> Decimal handling in f-textfield

packages/ketchup/src/f-components/f-cell/f-cell.tsx
Added TextArea tagName when value comes from event target
=> TextArea value from event target

packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx
Set an initial value for timepicker in INP
=> initialValue for timeAdapter

packages/ketchup/src/components/kup-echart/kup-echart.tsx
- in setLegend, column titles are now used instead of column names
- in setPieOptions, we now parse starting from first index and we add a nullcheck on parseFloat
- when type is 'Line', we now numberify safely the values.
- in setOptions, we improve tooltip formatting and we ensure legend values match with names in data object.
https://youtu.be/Sbf_uNR37bk
=> fix: legends and tooltips in graphs

packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx
=> fix/ added quotes into QuerySelector

packages/ketchup/src/components/kup-echart/kup-echart.tsx
- Tooltip is now based on item and not on axis for most charts.
- Axis labels are formatted considering browser's locale
=> fix: tooltip and axis labels

packages/ketchup-showcase/src/views/components/advanced/echart/examples/EchartArea.vue, packages/ketchup-showcase/src/views/components/advanced/echart/examples/EchartBar.vue, packages/ketchup-showcase/src/views/components/advanced/echart/examples/EchartDemo.vue, packages/ketchup-showcase/src/views/components/advanced/echart/examples/EchartEvents.vue, packages/ketchup-showcase/src/views/components/advanced/echart/examples/EchartHBar.vue, packages/ketchup-showcase/src/views/components/advanced/echart/examples/EchartLine.vue, packages/ketchup-showcase/src/views/components/advanced/echart/examples/EchartPie.vue, packages/ketchup-showcase/src/views/components/advanced/echart/examples/EchartRadar.vue, packages/ketchup-showcase/src/views/components/advanced/echart/examples/EchartScatter.vue, packages/ketchup/src/echart.html
Solves problems with echarts in k showcase simply adding series to their props.
=> fix: showcase graphs

packages/ketchup/src/components/kup-card-list/kup-card-list.scss
I tryed to apply the same css property in webup.jsf and nothing happen, then I think that's ok.
=> fix: remove scrollbar in dash list

packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-calendar/kup-calendar.tsx
- Add a prop to manage changeView visibility
=> feat / enableChangeView

packages/ketchup/src/components/kup-text-field/kup-text-field.tsx, packages/ketchup/src/f-components/f-cell/f-cell.tsx, packages/ketchup/src/f-components/f-text-field/f-text-field-declarations.ts, packages/ketchup/src/f-components/f-text-field/f-text-field.tsx, packages/ketchup/src/managers/kup-data/kup-data-declarations.ts, packages/ketchup/src/managers/kup-math/kup-math.ts
Task description:
"FUN: F(EXD;*SCO;) 1(;;) 2(MB;SCP_SCH;WETEST_I04) 4(;;SH1).         
Il campo "InputNumber 3 dec" ha 3 decimali (nella colonna del json di as400proxy la lunghezza è impostata correttamente). Il comportamento del campo numerico ketchup fa si che non si riescano a digitare i decimali."
=> Fix: Input textfield decimals

packages/ketchup/src/components/kup-echart/kup-echart.tsx
adds checks to handle undefined data in the calendar chart function, preventing errors when date or value are missing
=> fix: kup-echarts handle undefined date

packages/ketchup/src/components/kup-text-field/kup-text-field.tsx, packages/ketchup/src/f-components/f-cell/f-cell.tsx, packages/ketchup/src/f-components/f-text-field/f-text-field-declarations.ts, packages/ketchup/src/f-components/f-text-field/f-text-field.tsx, packages/ketchup/src/managers/kup-math/kup-math.ts
=> Revert "Fix: Input textfield decimals"

packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx
Disabled footer in an absolute layout inputPanel's table and moved prop in cell.data
=> minor fix/Removed tbl footer in absolute inputPanel

packages/ketchup-react/components.ts, packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-combobox/kup-combobox.tsx
- Unify functions 
- Reset kup-combobox to re-trigger the event
=> feat / combobox / unify functions

packages/ketchup/src/f-components/f-cell/f-cell.tsx, packages/ketchup/src/utils/cell-utils.ts
Adding decode in non editable EXU cells by using displayMode like in kup-list
=> feat/decode in non-editable EXU cells

packages/ketchup/src/components/kup-image-list/styles/kup-image-list-main.scss
Remove a margin-top on the whole kup-image-list that has bad effect on visual layout
=> feat / remove margin

packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx, packages/ketchup/src/f-components/f-cell/f-cell.tsx
Created fallback for EDT shape using a textArea despite editor component
=> LS25000037 - create fallback forma grafica EDT 

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/components/kup-editor/kup-editor.tsx, packages/ketchup/src/managers/kup-data/kup-data.ts
Added additional checkings when objects are null
=> LS25000082: *TICKET*Error during data convertion. Cannot read prop. of undefined

packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx
This reverts commit 6936005633033485d466361259e86450fbd4df03.
=> Revert "bugfix: hide hidden columns only during render"

packages/ketchup/src/managers/kup-keys-binding/kup-keys-binding.ts
Cleared buffer of pressed keys when keyUp event triggers.
https://docs.google.com/document/d/1ZIBgh2OOVt9nY63lJCc6o_i2R6P6nBJGyQjMiSiApzE/edit?tab=t.0#bo okmark=id.abi4kop7y4u5
=> LS25000104: analisi casistica invio non funzionante INL

packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx
hide hidden columns in input panel only during render with column check
=> LS25000124/LS25000109: hide hidden columns in input panel only during render

packages/ketchup/src/components/kup-date-picker/kup-date-picker.tsx
Fixed problem with kup-date-picker shape that did not render error inside input panel, also, in console, there was a DOM error on "insertBerfore" method.
I've found out the solution on this thread: https://stackoverflow.com/a/59845764 
Indeed, setting an id for the wrapper div of kup-card resolved the problem
=> LS25000108: forma grafica cal non visualizza errore

packages/ketchup/src/components/kup-editor/kup-editor.tsx, packages/ketchup/src/f-components/f-cell/f-cell.tsx
Fixed error: "bad request Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value" when submitting/modifying an action.
These error was caused by unescaped characters inside textArea
=> LS25000175: bad request Illegal unquoted character

packages/ketchup/src/f-components/f-cell/f-cell.tsx, packages/ketchup/src/f-components/f-text-field/f-text-field-declarations.ts, packages/ketchup/src/f-components/f-text-field/f-text-field.scss, packages/ketchup/src/f-components/f-text-field/f-text-field.tsx
Fixed textArea dimensions when used as fallback component for EDT shape through css prop
=> LS25000175: fix on textArea dimensions - bad request Illegal unquoted character

packages/ketchup/src/f-components/f-cell/f-cell.tsx, packages/ketchup/src/f-components/f-text-field/f-text-field-declarations.ts, packages/ketchup/src/f-components/f-text-field/f-text-field.scss, packages/ketchup/src/f-components/f-text-field/f-text-field.tsx
- Removed temporary property editorFallback 
- Added sizing handling for textarea
=> LS25000175: fix/textarea sizes

packages/ketchup/src/components/kup-data-table/kup-data-table-helper.ts, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/components/kup-tree/kup-tree.tsx, packages/ketchup/src/managers/kup-math/kup-math-helper.ts, packages/ketchup/tests/resources/mock/kup-data-dataset-with-people-nrs-dates.json, packages/ketchup/tests/unit/components/kup-data-table/kup-data-table-helper-totals.spec.ts
- Sanitizer : use a simple parser to handle comma and negative numbers properly
- Pass column to calcTotals to retrieve decimals to fix the decimals in the totals
=> LS25000164 : feat : adjust kup-data-table totals

packages/ketchup/src/f-components/f-cell/f-cell.tsx, packages/ketchup/src/f-components/f-image/f-image.tsx
Fixed re-revert of https://github.com/smeup/ketchup/pull/2434
=> LS25000278: Fix `cell.data.resource` overwrites `cell.icon`

packages/ketchup/src/f-components/f-cell/f-cell.tsx
Correct a f-cell behaviour that broke the input-legacy event
=> NC : fix : except cell shape memo

packages/ketchup/src/components/kup-data-table/styles/kup-data-table-main.scss, packages/ketchup/src/f-components/f-cell/f-cell.scss
upgrade the f-cell management inside the legacy look behaviour
=> feat / data-table legacy look

packages/ketchup/src/components/kup-data-table/kup-data-table-helper.ts, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/components/kup-tree/kup-tree.tsx, packages/ketchup/tests/resources/mock/kup-data-dataset-mat-with-formulas.json, packages/ketchup/tests/unit/components/kup-data-table/kup-data-table-helper-totals.spec.ts
- Fix undefined totals
- Fix calc totals columns order
- Update related unit test
=> LS24005827: Fix/mat totals default and total columns order

packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-toolbar/kup-toolbar.scss, packages/ketchup/src/components/kup-toolbar/kup-toolbar.tsx, packages/ketchup/src/components/kup-toolbar/readme.md
Clean code and manage icons inside toolbar component
=> LS25000490 : feat : clean code and manage icons

packages/ketchup/src/components/kup-toolbar/kup-toolbar.scss, packages/ketchup/src/components/kup-toolbar/kup-toolbar.tsx
Manage the disabled node prop inside toolbar
=> LS25000487 : feat : manage disabled node prop 

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx
Clicking on a row-action icon ( both expander or action-icon ) it will emit the event to select the corresponding row.
=> LS25000480 : feat : row action selected row

packages/ketchup/src/components/kup-date-picker/kup-date-picker.tsx, packages/ketchup/src/utils/kup-column-menu/kup-column-menu.ts
Solves broken wjs tests removing a (now) useless condition.
Solves a problem with date picker clearing
As asked, increased max length of filter inputs.
=> LS25000457: fix: datepicker tests

packages/ketchup/src/components/kup-data-table/styles/kup-data-table-main.scss
- Reduce the size of the group and total rows in the Data Table
=> LS25000617: Fix/mat group and total rows size

packages/ketchup/src/utils/filters/filters-column-menu.ts, packages/ketchup/src/utils/filters/filters-rows.ts, packages/ketchup/src/utils/filters/filters.ts
Fixed some conversions for date/time/timestamp formats when used in column menu
=> LS25000457: Fixes filtri colonna matrice

packages/ketchup/src/components/kup-data-table/kup-data-table-helper.ts
This PR contains a temporary fix to complete test exu and inp testing in webup.js. Then all adapters can be standardized
=> feat: add adapter to data-table to handle aml and cml

packages/ketchup/src/components/kup-calendar/kup-calendar.tsx
- Add event to onToday
- Fix undefined state
=> LS25000872: Fix/kup-calendar-on-today

packages/ketchup/src/utils/filters/filters-column-menu.ts, packages/ketchup/src/utils/filters/filters.ts
Fixed: 
- `filter = ''` while matching value
- checkbox filter `filter = ''` is not removed
=> LS25000885: Filter with empty filter value

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx
Disable onRowclick event when click on row action
=> LS25000875 - fix: disable event onRowclick when click on codver

packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx
Pressing Enter on a field inside INP now calls the update service.
=> LS25000915: INP/EXU - Invio su forme grafiche

packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx
Fixed a missed check in multiple acp
=> LS25000945: Unchecked undefined in autocomplete multiplo

packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-autocomplete/kup-autocomplete.tsx, packages/ketchup/src/components/kup-chip/kup-chip.tsx, packages/ketchup/src/components/kup-chip/readme.md, packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx, packages/ketchup/src/f-components/f-cell/f-cell.tsx, packages/ketchup/src/f-components/f-chip/f-chip-declarations.ts, packages/ketchup/src/f-components/f-chip/f-chip.tsx
Handled DescrMode for AML shape.
Also, removed 'displayId' prop for kup-chip and implemented new prop 'displayMode'
=> LS25000976: Aml gestione Ext DescrMode

packages/ketchup/src/components/kup-chip/kup-chip.tsx, packages/ketchup/src/components/kup-chip/styles/kup-chip-main.scss
=> LS25000892: fix: label css

packages/ketchup/src/components/kup-list/kup-list.tsx
- Click to open the dropdown list
- Select an item with the keyboard and press Enter
- Click to open the dropdown list and type something in the global filter that does not occur in the dropdown list
- Press Enter
- Boom...
=> LS25001121: kup-list: - Fix error when the user performs these operations

packages/ketchup/src/f-components/f-cell/f-cell.tsx
=> NC: feat: extend list display mode

packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx
This feature is related to the issue #2562
=> ***FeatureFlag***: INL less monospace

packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx, packages/ketchup/src/f-components/f-text-field/f-text-field-declarations.ts, packages/ketchup/src/f-components/f-text-field/f-text-field.tsx
This feature is related to the issue #2562
=> ***FeatureFlag***: INL less monospace ||

packages/ketchup/src/components/kup-box/kup-box.tsx, packages/ketchup/src/components/kup-card/box/kup-card-box-1.scss, packages/ketchup/src/components/kup-card/box/kup-card-box-2.scss, packages/ketchup/src/components/kup-card/box/kup-card-box-3.scss, packages/ketchup/src/components/kup-card/box/kup-card-box-4.scss, packages/ketchup/src/components/kup-card/box/kup-card-box-5.scss, packages/ketchup/src/components/kup-card/box/kup-card-box-6.scss, packages/ketchup/src/components/kup-card/box/kup-card-box-7.scss, packages/ketchup/src/components/kup-card/box/kup-card-box-8.scss, packages/ketchup/src/f-components/f-cell/f-cell.tsx
Fixes a problem with duplicate items inside cards
Fixes a problem with progress bar not shown inside boxes
=> LS25001320: fix boxList default layouts

packages/ketchup/src/components/kup-box/kup-box.tsx
Solves a problem in box.cy about boxes with missing cardData
=> LS25001320: fix: boxes tests

packages/ketchup/src/components/kup-echart/kup-echart.tsx
Not showing months anymore in charts but full iso dates
=> LS25001383: Errore date in grafici

packages/ketchup/src/components/kup-toolbar/kup-toolbar.scss, packages/ketchup/src/managers/kup-dynamic-position/kup-dynamic-position.ts
Ensure toolbar submenus remain visible when near the right edge of the viewport
=> LS25001777: fix: kup-toolbar submenu dynamic position

packages/ketchup-react/components.ts, packages/ketchup/src/accordion.html, packages/ketchup/src/assets/accordion.js, packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-accordion/kup-accordion.tsx, packages/ketchup/src/components/kup-accordion/readme.md, packages/ketchup/src/components/kup-tab-bar/kup-tab-bar.tsx, packages/ketchup/src/components/kup-tab-bar/readme.md
This pull request introduces several updates to the `kup-accordion` and `kup-tab-bar` components, focusing on feature removal, code improvements, and new functionality for nested accordions. The most significant changes include the removal of the `infoiconclick` event, enhancements to the `kup-accordion` logic for better handling of nested accordions, and updates to the documentation and examples.
* Removed the `kup-accordion-infoiconclick` and `kup-tabbar-infoiconclick` events, along with their associated code, as they were deemed unnecessary. (`[[1]](diffhunk://#diff-12e77546f07f64b382b398ec8e093362d001c1f1cefcb762a74c715eea2a6096L92)`, `[[2]](diffhunk://#diff-12e77546f07f64b382b398ec8e093362d001c1f1cefcb762a74c715eea2a6096L106)`, …
=> LS25002169: kup-accordion, kup:tab-bar: refactoring, removed unused code

packages/ketchup/src/f-components/f-radio/f-radio.scss
Added flex wrap to horizontal radio buttons
=> LS25003053: Wrap long horizontal radio buttons

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx
Removed a condition that prevented the execution of click events on a J4ICO column
=> LS25003563/fix: removed condition that prevents click event on J4ICO column

packages/ketchup/src/components/kup-button/readme.md, packages/ketchup/src/components/kup-htm/readme.md, packages/ketchup/src/managers/kup-data/kup-data.ts
VO;COD_VER cells with blank 'k' value should not be rendered
=> LS25003646: Fix: VO;COD_VER cells with blank 'k' value

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx
Fix index in case single codver with only icon render (not in list)
=> fix: change index in click vocodver
