smeup/ketchup

packages/ketchup-showcase/src/App.vue, packages/ketchup-showcase/src/views/dataTable/DTBasic.vue, packages/ketchup-showcase/src/views/dataTable/DTFilters.vue, packages/ketchup/package-lock.json, packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-data-table/kup-data-table-helper.ts, packages/ketchup/src/components/kup-data-table/kup-data-table.scss, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/components/kup-data-table/readme.md, packages/ketchup/src/components/kup-html/kup-html.tsx, packages/ketchup/src/components/kup-portal-instance/kup-portal-instance.tsx, packages/ketchup/tests/e2e/data-table/data-table-basic.e2e.ts, packages/ketchup/tests/unit/data-table/data-table-filter.spec.ts
Added sticky header functionality for the table header.
Added control on filter functionality to show cells with null values when filter is set to `''`.
@casetta-smeup there is a strange error not always occurring when running `data-table-basic.e2e.ts > 'cell has right click button'`. Can you tell me if this test some times fails also for you?
=> Matrix empty filter sticky header

packages/ketchup-showcase/src/views/box/BoxClasses.vue, packages/ketchup/src/components/kup-badge/readme.md, packages/ketchup/src/components/kup-box/kup-box.scss, packages/ketchup/src/components/kup-box/readme.md, packages/ketchup/src/components/kup-btn/readme.md, packages/ketchup/src/components/kup-button/readme.md, packages/ketchup/src/components/kup-calendar/readme.md, packages/ketchup/src/components/kup-checkbox/readme.md, packages/ketchup/src/components/kup-chip/readme.md, packages/ketchup/src/components/kup-combo/readme.md, packages/ketchup/src/components/kup-data-table/readme.md, packages/ketchup/src/components/kup-fld/readme.md, packages/ketchup/src/components/kup-graphic-cell/readme.md, packages/ketchup/src/components/kup-html/readme.md, packages/ketchup/src/components/kup-image/readme.md, packages/ketchup/src/components/kup-paginator/readme.md, packages/ketchup/src/components/kup-portal-instance/readme.md, packages/ketchup/src/components/kup-portal/readme.md, packages/ketchup/src/components/kup-progress-bar/readme.md, packages/ketchup/src/components/kup-radio-element/readme.md, packages/ketchup/src/components/kup-radio/readme.md, packages/ketchup/src/components/kup-text-input/readme.md, packages/ketchup/src/components/kup-tooltip/readme.md, packages/ketchup/src/components/kup-tree/readme.md
Applied to `kup-box`:
- ` .with-padding`, sets some padding/margins between box elements.
Applied to `.box-section`:
- `.left-aligned`, aligns content to the left;
- `.center-aligned`, aligns content to the center;
- `.right-aligned`, aligns content to the right.
=> CSS Classes for box

packages/ketchup-showcase/public/showcase.css, packages/ketchup-showcase/src/views/basic/button/examples/ButtonBasic.vue, packages/ketchup-showcase/src/views/basic/button/examples/ButtonIconVariant.vue, packages/ketchup/src/components.d.ts, packages/ketchup/src/components/wup-button/readme.md, packages/ketchup/src/components/wup-button/wup-button.tsx, packages/ketchup/src/components/wup-checkbox/wup-checkbox.tsx, packages/ketchup/src/components/wup-switch/wup-switch.tsx, packages/ketchup/src/components/wup-tab-bar/wup-tab-bar.scss, packages/ketchup/src/components/wup-text-field/wup-text-field.scss, packages/ketchup/src/index.html
- Fixed issue on Tab Bar displaying scroll area on Firefox and Edge (Material Design problem)
- Added textarea to JSON section of demo panel and improved look.
- Added new prop to button, iconoff. Changed value initialization in events for basic components.
- Added icon button in demo panel to switch display mode.
- Added title to demo panel icon button.
- Added copy to HTML demo panel. Updated button page with new prop.
- Fixed disabled color in textarea.
=> Info in comments

packages/ketchup/src/components/kup-tooltip/kup-tooltip.tsx
Il ritardo serve per rendere più accessibile l'utilizzo dei bottoni,
se l'utente non era particolarmente rapido nello spostamento
del mouse il tip si chiudeva prima che l'utente raggiungesse
i vari bottoni
=> Introdotto ritardo sulla chiusura del tip

packages/ketchup-showcase/src/mock/dataTable.ts, packages/ketchup-showcase/src/views/advanced/datatable/examples/DatatableColumnsWidth.vue, packages/ketchup-showcase/src/views/advanced/datatable/examples/DatatableGraphicCell.vue, packages/ketchup/src/components/kup-data-table/kup-data-table-declarations.ts, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx
Bonus:
- refactor(data-table): clean renderCell parameters
- fix(data-table): make graphic and chart cells adapt the column width when specified
Was adding the clickable class when I noticed a lot of confusion into the `renderCell` class, so I cleaned it up a bit.
While cleaning it, I noticed a bug with custom column width when applied to graphic and chart cells, so I fixed that one as well.
=> feat(data-table): add clickable class to cells when column is marked clickable

packages/ketchup/src/components/kup-chart/kup-chart-declarations.ts, packages/ketchup/src/components/kup-chart/kup-chart.tsx
google charts - bar charts - stacked option: if not set chart type from scheda (it means will be rendered a VBar chart) managed attribute stacked, like already done for HBar and VBar charts; chart type: ColumnChart
=> google charts - bar charts - stacked option

packages/ketchup/src/assets/tooltip.js, packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-crud/readme.md, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/components/kup-data-table/readme.md, packages/ketchup/src/components/kup-form/readme.md, packages/ketchup/src/components/kup-search/readme.md, packages/ketchup/src/components/kup-tooltip/kup-tooltip-declarations.ts, packages/ketchup/src/components/kup-tooltip/kup-tooltip.scss, packages/ketchup/src/components/kup-tooltip/kup-tooltip.tsx, packages/ketchup/src/components/kup-tooltip/readme.md, packages/ketchup/src/index.html, packages/ketchup/src/tooltip.html, packages/ketchup/src/utils/recalc-position.ts, packages/ketchup/stencil.config.ts
kup-data-table: manage one kup-tooltip element for all datatable cells; it moves when onMouseOver event fires
=> Tooltip tests

packages/ketchup-showcase/src/views/advanced/datatable/examples/DatatableFixedColumnsRows.vue
Example name: Fixed columns (2 columns and show-grid = Col)
=> Fixed columns example with totals in showcase

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx
**kup-data-table**: added property for customizing label displayed when table has no data
=> kup-data-table: added property for customizing label displayed when table has no data

packages/ketchup-showcase/.eslintrc.js, packages/ketchup-showcase/src/views/advanced/datatable/examples/DatatableFixedColumnsRows.vue, packages/ketchup-showcase/vue.config.js, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/components/kup-data-table/modules/kup-data-table-fixed-rows.scss, packages/ketchup/src/components/kup-data-table/modules/kup-data-table-main.scss
Here is a biref explanation regarding the solution for fixed header and borders in kup-data-table.
All browsers have an interesting issue in which sticky cells in combination with `border-collapse: collapse;` will not keep the border in place.
A possible solution would be to use pseudo elements, but this will make you struggle with many different behaviors across
different browser.
The most reliable solution is to set `border-collapse: separate;` in combination with `border-spacing: 0;` and apply the style of the borders to the single cells, since the table can be scrolled and is not reliable to have borders set onto the table itself, when the table must have sticky cells.
Therefore, inside these commits you will find a rework on how table borders are set in CSS.
I'm asking for your …
=> data-table-fixes [menu, fixed horizontal totals, fixed columns and cells borders]

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx
A small fix for Safari and kup-data-table: basically Safari starts positioning the sticky cells not from the start of the table but rather the start of the tbody element, even though the tbody element does not have the `position: sticky;` style.
Verify if the fix is working also for you (I've tested it on MacOS 10.15 Catalina and relative Safari browser).
=> fix(kup-data-table): sticky positioning for Safari

packages/ketchup/src/components/kup-text-field/kup-text-field.tsx, packages/ketchup/src/f-components/f-text-field/f-text-field.scss, packages/ketchup/src/f-components/f-text-field/f-text-field.tsx
fix class name id of icon linked to kup-text-field, confused with clear icon
=> fix class name id of icon linked to kup-text-field

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/components/kup-tree/kup-tree.tsx, packages/ketchup/src/utils/cell-utils.ts, packages/ketchup/src/utils/filters/filters-rows.ts
kup-data-table:
- globalFilter applyed on values contained only in visibile columns of the table
- checkboxes column filter bug: on click on a value, became selected 2 checkboxes; for solve this, modified compare strings function, like java (localCompareAsInJava()): took implementation of: java.lang.String.compareTo()
=> removed filter on hidden columns (kup-data-table); fix order values java-like

packages/ketchup/src/components/kup-data-table/kup-data-table-declarations.ts, packages/ketchup/tests/e2e/data-table/data-table-row-selection.e2e.ts
fixed errors on launching ketchup-showcase (?!)
=> kup-data-table e2e test for row select: skipped for now

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx
…n no action fired (kup-data-table).
=> Bugfix: clickHandler and contextMenuHandler didn't return details when no action fired (kup-data-table).

packages/ketchup/package-lock.json, packages/ketchup/package.json, packages/ketchup/src/managers/kup-manager/kup-manager-declarations.ts, packages/ketchup/src/managers/kup-manager/kup-manager.ts
This reverts commit 7c9f504681ea54a5b136710ae203bf00223debde.
=> Revert "Removed redundant dependency (ResizeObserver fully supported by browsers now, natively)." Apparently not.

packages/ketchup-react/package.json, packages/ketchup-react/tsconfig.json
Fix ketchup-react package build process. Use `esnext` and declare module and typings files into `package.json`.
=> Fix tsconfig and package json

.github/workflows/test.yaml
This workflow will test ketchup by using the command: `npm run k:test:unit`
It will be triggered on PR opening against the master and develop branches.
In addiction you can launch the workflow also through the github Actions panel.
=> Test workflow

packages/ketchup/src/components/kup-image-list/kup-image-list.tsx
When passed by WebUP, the int row value was 0 by default (being int a primitive type), so the if was basically bypassed every time the iml view was set to Ketchup, ruining the whole iml grid.
=> IF update kup-image-list.tsx

packages/ketchup/src/components/kup-pdf/kup-pdf.tsx
This prop manages the "withCredentials" attribute in the pdfJSLib.getDocument, default value is set as True.
=> kup-pdf : new prop sendCredentials

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/managers/kup-data/kup-data.ts, packages/ketchup/tests/resources/mock/kup-data-dataset-with-commands.json, packages/ketchup/tests/unit/components/kup-data-table/kup-data-table-row-actions.spec.ts
If there is only one action, it shows only icon in row.
It there are more actions with only icons, show them in row.
Otherwise, actions will be inside dropdopwn layout.
Plus, refactoring
=> Data table actions different cases

packages/ketchup/src/assets/image-list.js, packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-image-list/kup-image-list.tsx, packages/ketchup/src/components/kup-image-list/styles/kup-image-list-main.scss
THIS PR NEEDS TO BE ACCEPTED WITH ITS WEBUP.JSF COUNTERPART:
[(https://github.com/smeup/webup-project/compare/develop...Add_IMLResponsiveColumns?expand=1)](https://github.com/smeup/webup-project/compare/develop...Add_IMLResponsiveColumns?expand=1)
Prop Column for kup-image-list is now a KupDataNode and has 3 possibilities for its value:
- "N" : acts as the previous one
- "N;N" : first number is used for phone and tablet, second one for pc
- "N;N;N" : first number for phone, second for tablet, third for pc
=> Feat/image list/responsive columns prop

packages/ketchup/src/f-components/f-text-field/f-text-field.scss
restore default for textfield as 100%.
Fit content will be passed in the client where needed
=> feat / change content width default

packages/ketchup/src/components/kup-autocomplete/kup-autocomplete.tsx, packages/ketchup/src/components/kup-combobox/kup-combobox.tsx
bugfix: 
Component Autocomplete e combobox error: `kup-autocomplete: Uncaught TypeError: Cannot read properties of undefined (reading 'trim')`
=> fix: handle error on kup-comboboxe and kup-autocomplete

packages/ketchup/src/components/kup-tab-bar/kup-tab-bar.scss
do not flex tab on tablet/desktop size. It'll only flex on mobile
=> feat / tab-bar flex

packages/ketchup/src/components/kup-input-panel/kup-input-panel.scss, packages/ketchup/src/f-components/f-cell/f-cell.scss
Added css property to set width property for every cell to fit-content instead of 100% in input panel.
=> fix input panel layout: fit-content

packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx
When an INP had absolute field positioning (like in InputLegacy) and width was null the fields were hidden.
This happened because the returned div wrapping { content } could not size itself correctly without a default width.
Now if a width is found the "wrapper" div is returned with also the other attributes, if a width is not found the div is removed because it will only hide its contents.
Right now height is not relevant because of the 40ch passed as default to the "input-panel--absolute" class
=> fix/absolute pos INP not showing fields without width

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/managers/kup-data/kup-data-declarations.ts
Needs https://github.com/smeup/webup.js/pull/717 pr changes to be effective
Managed new attribute useAs for editable data-table.
The value is found in columns and it affects the cells under the column in 2 ways:
- useAs = "Dec" : the cell is never editable, in both row visualization and insert (usually this value is calcuated by backend)
- useAs = "Key" : cell is only editable when i'm adding a row to the table. If the row is in "visualization mode" the cell is not editable
=> Feat/useAs in visualization and row insert editableTable

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx
Changes made to how the editability of a cell is assigned, now the priority is this:
1) useAs - only used for EXU
2) cell.isEditable - if useAs is missing, cell editability is not changed
3) column.isEditable - if for some reason, cell.isEditable and useAs are missing, editability is taken from the column
=> Fix/CellEditability was overwritten by the ColumnEditability

packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/components/kup-data-table/readme.md
added a new method to retrieve last focused row. 
If there's no row focused it will be the first row, otherwise it will be set in the `clickHandler` method.
=> feat(kup-data-table): added retrieve last focused row

packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-time-picker/kup-time-picker.tsx
Setting prop manageSeconds of timepicker always to true
=> timepicker prop manageSeconds to default: true

packages/ketchup/src/components/kup-data-table/kup-data-table-helper.ts, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx
In Updatable table return `after` with only set values, avoid invisible columns in diffs and add row id only if there's no id in at least one row.
=> bugfix: kup data table - new row id and diff

packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx
If error is not a mandatory type error, will be checked if currentValue is set in CMB/ACP shape.
If yes, the error sent by backend will be showed, else not.
This implementation has been done because even if an error is resolved in a CMB shape in INP component, error will always be sent inside data, even if it's resolved.
=> Set error only if value is present in CMB/ACP shape

packages/ketchup/src/components/kup-data-table/kup-data-table-helper.ts
In `kup-data-table-helpers` the condition of existing options is removed for always map shapes. The control of existing options is inside the util method
=> bugfix: remove options condition in decorateDataTable

packages/ketchup/src/components/kup-echart/kup-echart.tsx
- Adds padding handling on graph legend, based on its position
- Now legend turns automatically in a scrollable one when space is not enough.
- Adds word break on overflow for graph title
=> feat: add padding, scroll on graph legend

packages/ketchup/src/components/kup-echart/kup-echart.tsx
- Now when legend is placed top or bottom its orientation is horizontal, viceversa for right and left.
- When container size (width) is too small, legend is placed on the bottom side by default.
- Pie chart config and readability was improved: it does not show labels nor legend items when the value for an item equals 0.
https://youtu.be/1O-wDcUvoWs
=> fix: legend and pie graph

packages/ketchup/src/components.d.ts, packages/ketchup/src/f-components/f-text-field/f-text-field-declarations.ts, packages/ketchup/src/f-components/f-text-field/f-text-field.tsx
Set the default `autocomplete: "off"` to disable suggestions
=> feat: add autocomplete props to customize suggestion

packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx
By adding rowsPerPage: (row number) and showPaginator: false the table paginator in an absoluteLayout inputPanel is removed and all rows are shown
=> Fix/removing paginator and showing all rows in INL data table

packages/ketchup/src/components/kup-echart/kup-echart.tsx
Solves a problem with the tooltip still being visible after the execution of a Dynamism in webup.js.
We simply dispose the graph in unmount lifecycle hook.
=> fix: tooltip visible after dinamism

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx
Managed the display of "codver" in the kup-data-table component, ensuring correct handling of its visibility both when the `visibleColumns` prop is provided and when it is not.
=> fix: double vocodver in kup-data-table

packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx
By specifying tableHeight the table fixed headers are now active (if not the scroll was being done in the whole inp field and not only on the table)
=> minor-fix/Fixed header in absolute INP data-table

packages/ketchup/src/components/kup-list/kup-list.tsx
ArrowDown and ArrowUp eventListener was attached twice to the window (and consequentially fired twice), a problem very likely due to Stencil's @Listen decorator.
The solution applied was to make the listenKeydown method (the one previously used in @Listen) as a private one and putting it in the onKeyDown attribute of the div with id="kup-component"
=> fix/double arrowDown event in kup-list

packages/ketchup/src/components/kup-input-panel/kup-input-panel.scss, packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx
Manage inside the input panel the `number` ogg ( NR ) in non-editable mode. 
Whenever you rendere a LBL, and it's a number, the content is right-aligned
=> feat / manage ogg nr in label

packages/ketchup/src/managers/kup-math/kup-math.ts
fixed a behavior when backend returns numbers in scientific notation (ex: from 1.132614403E7 to 11,326,144.03).
Now numbers of this type will be displayed correctly using Number() js constructor
=> Number in scientific notation

packages/ketchup/src/components/kup-autocomplete/kup-autocomplete.tsx, packages/ketchup/src/components/kup-combobox/kup-combobox.tsx, packages/ketchup/src/components/kup-list/kup-list-helper.ts, packages/ketchup/src/components/kup-list/kup-list.tsx
Fixes list:
- kup-list issues with focusNext and focusPrevious methods generating an undefined exception when called with keyboard navigation.
- when opening a list from ACP and CMB when i press ArrowDown or ArrowUp to move focus from textField to kup-list the first focused element is the one previously selected by the user.
- optimized the Kup-List helper method with the task of creating the shown value based on the display mode
- fixed an error that occurred when typing an unexisting value in the acp. If i typed "hello" the shown value was "hello - hello", resulting in a confusing false decode, with this fix the value shown would be only "hello", without the "- hello" suffix
=> fix/CMB and ACP focus and check fixes

packages/ketchup/src/components/kup-autocomplete/kup-autocomplete.tsx
By closing the list directly in the kup-change the selection event didn't correctly select the list item clicked when the input value changed
=> minor-fix/Autocomplete missed selection for list close

packages/ketchup/src/components/kup-autocomplete/kup-autocomplete.tsx
An empty string is now always accepted by an ACP.
=> fix/Always allow blank values in ACP

packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx
hidden columns in input panel only during render, and not from after, to let use values of hidden columns, for example, in dynamic objects
=> LS25000124/LS25000109: hide hidden columns in input panel only during render

packages/ketchup/src/f-components/f-text-field/f-text-field.scss
In INL when a field was in error, the usual field error outline was "surpassed" by the field outline of the focus.
Now when the focus is set on a field in error, the border keeps the error outline
=> minor-fix/TextField - Error outline over field focus outline

packages/ketchup/src/components/kup-data-table/kup-data-table-state.ts, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx
- Adds `visibleColumns` to `KupDataTableState` in order to preserve hidden and moved columns.
- Changes the way columns are hidden to tackle a problem that occurred when trying to remove a column name present more than once in `visibleColumns` string array.
https://youtu.be/u4ieVLH_nA4
Related to: https://github.com/smeup/webup.js/pull/1061
=> LS25000013: fix: visible columns handling

packages/ketchup/src/f-components/f-cell/f-cell.tsx, packages/ketchup/src/utils/cell-utils.ts
When an FCell of type ACP or CMB is disabled, instead of always displaying the code, it retrieves the value to display by looking at the display mode (keeping the DESCRIPTION as default when nothing is found).
=> LS25000174: changed cellValue for disabled ACP and CMB

packages/ketchup/src/f-components/f-text-field/f-text-field.tsx
- Identify the NumpadDecimal event
- If the value contain the separator it won't trigger the keyboard event
- Otherwise it'll include the decimalSeparator inside the input field.
_Another solution could have been swapping the numpadDecimals event with the corresponding decimalSeparator keyboard event but, at this time, it seems it doesn't work._
=> feat / manage keyboard event

packages/ketchup/src/button.html, packages/ketchup/src/f-components/f-button/f-button.scss
manage the color of the icon whenever the kup-neutral class is active.
=> feat / kup neutral icons color

packages/ketchup/src/components/kup-data-table/styles/kup-data-table-main.scss
Manage background error inside the `kup-data-table` component while legacy-look is true. This change will render a transparent background that will render the red background
=> feat / manage background in table

packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx
The issue appeared while analyzing an INL that is closed by clicking the X button. It was discovered that the KeyboardEvents of the closed kup-input-panel remain active, and upon activation, they trigger inconsistent behaviors. With this fix, the events are removed when the component is destroyed.
=> fix/handled deletion of registered KeyboardEvents Input Panel

packages/ketchup/src/components/kup-date-picker/kup-date-picker.tsx, packages/ketchup/src/components/kup-date-picker/styles/kup-date-picker-main.scss
This fix is related to the `kup-date-picker` component.
Due to the new introduced div `id="_card"`, it will render a gap of 4px also between the input and the card ( which is the visual date selector ) while the card is not.
=> Fix/kup date picker/fix div height

packages/ketchup/src/components/kup-input-panel/kup-input-panel.scss, packages/ketchup/src/f-components/f-cell/f-cell.tsx, packages/ketchup/src/f-components/f-checkbox/f-checkbox.scss
`f-checkbox` is now used on absolutely-positioned INP cell.
=> LS25000015: Fix `f-checkbox` legacy look CSS

packages/ketchup/src/f-components/f-text-field/f-text-field.tsx
Fixes an issue with the datepicker component in an error state (INL).
The issue was caused by a div for the helper text being added below the field, resulting in an overflow. This behavior was unexpected, as the case analyzed involved Input Legac.
The fix ensures that the `setHelper` function considers `props.legacyLook` to conditionally return the helper text div. Additionally, a brief method documentation has been added for clarity.
https://youtu.be/SMLUQn814d8
=> LS25000198: fix: datepicker error state style

packages/ketchup/src/components/kup-card/standard/kup-card-standard-17.scss
With the max height set in that way if the card contained a scrollable list (like in the case of a VO;COD_VER) two scrollbars were generated, one caused by the list's max height, the other by the card's max height (scroll-list class)
=> LS25000069: Fix COD_VER double scrollbar

packages/ketchup/src/components/kup-autocomplete/kup-autocomplete.tsx, packages/ketchup/src/components/kup-combobox/kup-combobox.tsx
This PR solves a problem with CMB and ACP that occurs when their list is opened for the second time.
This happened because both ACP and CMB are not a single component, but the union of kup-list and f-text-field, so when the focus went from f-text-field to kup-list the blur event was triggered, the check was triggered, and the component refreshed (closing the list and forcing the user to re-close and re-open the list to properly select again).
The simplest solution found was to trigger the blur (and consequently the *CHECK) only when the list is actually closed
Issue where the problem was described
https://github.com/smeup/ketchup/issues/2368
=> LS25000375: ACP and CMB blurEvent only when list is closed

packages/ketchup/src/components/kup-autocomplete/kup-autocomplete.tsx
Conditionally adds a prop to FTextFieldProps in `kup-autocomplete` to adapt the size of the input based on the current displayedValue
LS25000233 - Acp non adatta la dim nel caso di codice+descr
=> LS25000233: fix: acp dynamic size

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/f-components/f-cell/f-cell.scss, packages/ketchup/src/f-components/f-cell/f-cell.tsx
Adds a couple event handlers to `#f-cell__content` div in `f-cell` to add a clickable image only onMouseEnter.
This is done manually creating elements due to Stencil limitations in 
- using a State in Functional Components
- creating Node instances from VNode instances returned from h() function when trying to use `FImage`
Any suggestions on how to improve this handling?
`kup-image` is removed as mouse leaves the cell.
`kup-card` rendered on click is now anchored to `kup-image` parent element to preserve its dynamic positioning.
SAL video 1: https://youtu.be/7uvi3Qq4HG4
=> LS25000332: feat: datatable performances cell action

packages/ketchup/src/components/kup-tab-bar/kup-tab-bar.tsx
removed forced 24px tab-bar icon size.
Restore to 16px
=> NC : feat : manage img tab-bar icon size

packages/ketchup/src/components/kup-input-panel/kup-input-panel.e2e.ts, packages/ketchup/src/components/kup-input-panel/kup-input-panel.scss, packages/ketchup/src/f-components/f-cell/f-cell.tsx, packages/ketchup/src/f-components/f-text-field/f-text-field.scss, packages/ketchup/src/f-components/f-text-field/f-text-field.tsx
Fixed textarea sizes in input panel component and resolved error CTRL-CHAR-10 also for STRING shapes in fcell.
It can be tested in ges_de10 with this fun:
F(EXD;*SCO;) 1(AR;;AA101752) 2(MB;SCP_SCH;XBRARTI_01) P(AziExe(02) CloFin(Yes)) SS(CONAP() Context() CGr(WUP) ID({webup}))
=> LS25000175: TextArea sizes in INP & illegal char for string shape

packages/ketchup/src/components/kup-date-picker/kup-date-picker.tsx, packages/ketchup/src/utils/filters/filters-declarations.ts, packages/ketchup/src/utils/filters/filters.ts, packages/ketchup/src/utils/kup-column-menu/kup-column-menu.ts
- The filter regex now ignores spaces at the beginning, at the end, and between the operator and the quoted value.
- Spelling is now correct :)
=> LS24005508: minor-fix: ignore spaces in filter string

packages/ketchup/src/components/kup-input-panel/kup-input-panel-declarations.ts, packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx
When #mapData was called in DataTableAdapter in order to correctly render cells of TBL, layout was not passed and so the fieldLabel was set to the Col.Title and not null. 
The test case was a tbl with checkboxes because Checkbox is the only graphic form usable in TBL whose adapter accepts label.
By passing the layout via DataTableAdapter the (layout.absolute) condition is now corrrectly checked and so fieldLabel is now passed correctly as null.
All tests on Webup.JS with this change passed
=> LS25000073: fix label in tbl checkbox - INP layout absolute

packages/ketchup/src/f-components/f-cell/f-cell.scss
Fix made in order to avoid "collapsed" data table rows
=> LS25000449: fcell min height for datatable row height regulation

packages/ketchup/src/components/kup-combobox/kup-combobox.tsx, packages/ketchup/src/components/kup-input-panel/kup-input-panel-declarations.ts, packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx, packages/ketchup/src/components/kup-list/kup-list.tsx, packages/ketchup/src/f-components/f-cell/f-cell-declarations.ts, packages/ketchup/src/f-components/f-cell/f-cell.tsx
*CHECK on blur created problem in CMB because of the iconClick opening the list but at the same time switching the focus from textField to icon (triggering blur, *CHECK and making the list not open correctly)
In order to fix this, a list of changes has been made:
- **Changed onBlurHandler to manageInputPanelCheck**: accepting an event and one string between "blur" and "itemclick" in order to differentiate the checks to make based on the type of event captured.
- **CheckConditionsByEventType const** : The controls used by manageInputPanelCheck are located in this const, declared in kup-input-panel-declarations. By changing the conditions there, the logic also changes in the method.
- **F-Cell changes**: in order to give the correct event payload to the inputPanel f-cell changes has been …
=> LS25000375: CMB *CHECK on itemclick - kuplist utility features

packages/ketchup/src/components/kup-box/kup-box-declarations.ts
Update type `columns` in `KupBoxSection` interface from `number` to `string`
=> fix: LS25000413 - change sections columns prop type

packages/ketchup/src/components/kup-autocomplete/kup-autocomplete.e2e.ts, packages/ketchup/src/components/kup-autocomplete/kup-autocomplete.tsx, packages/ketchup/src/components/kup-combobox/kup-combobox.tsx, packages/ketchup/src/components/kup-input-panel/kup-input-panel.e2e.ts
- Lists in acp and cmb now always show both Code and Description.
- Size of acp field now depends on DisplayMode, if not set using sub-component props
=> LS25000447: fix: acp size and cmb list display

packages/ketchup/src/components/kup-autocomplete/kup-autocomplete.tsx, packages/ketchup/src/components/kup-combobox/kup-combobox.tsx, packages/ketchup/src/components/kup-input-panel/kup-input-panel-declarations.ts, packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx, packages/ketchup/src/f-components/f-cell/f-cell-declarations.ts, packages/ketchup/src/f-components/f-cell/f-cell.tsx
Added *CHECK on itemclick for ACP (in the same way it was done for the CMB)
Small optimization for the mapCells method in kup-input-panel and added a new reset() method call.
This call is right now only used for ACP and CMB and its task is to close every list found open to avoid visualisation or "data" errors caused by a simultaneous *CHECK and a list opening FUN
=> LS25000375: ACP check on itemclick - ACP and CMB list "reset" on check

packages/ketchup/src/components/kup-input-panel/kup-input-panel.scss
Fixed behavior in input panel when display is inline-flex and changed padding value.
An example is reachable at F(EXD;*SCO;) 1(CN;CLI;) 2(MB;SCP_SCH;C5D010_OGB) P(FUNZ(MOD) EIM(1)) in ges_de10.
=> LS25000486: campi input panel appiccicati ai bottoni

packages/ketchup/src/components/kup-input-panel/kup-input-panel.scss
Fixed wrong behavior of alignment in input panel when using inline-flex display.
The example can be reached at: F(EXD;*SCO;) 1(CN;CLI;) 2(MB;SCP_SCH;C5D010_OGB) P(FUNZ(MOD) EIM(1))
=> LS25000485: disalliineamento campo input panel

packages/ketchup/src/components/kup-combobox/kup-combobox.tsx
Fixed a problem where focus was not set on the filter on first combo opening by forcing it every time a list is opened
=> LS25000533: fix focus on cmb filter on first open

packages/ketchup/src/f-components/f-cell/f-cell.tsx
Removed unnecessary check in fcell for mapping data and update object adapter.
Now checkboxes in fun F(EXD;*SCO;) 1(VO;W_LANSILJS;MDI) 2(MB;SCP_SCH;W_LANSILJS) 4(;;MDI_001) in ges_de10 show correctly their value.
=> LS25000542: Errata visualizzazione chk in griglialbero

packages/ketchup/src/f-components/f-text-field/f-text-field.tsx
The textfield won't display the label inside the input panel with absolute layout.
The information is passed through the legacyLook prop
=> NC : feat : don't display label input panel abs

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx
Recalling from spotlight a scheda with an exu inside in ges_de10: 
F(EXD;*SCO;) 1(;;) 2(MB;SCP_SCH;WETEST_EXU) 4(;;CHKCMPINT)
and another one with an exu again: 
F(EXD;*SCO;) 2(MB;SCP_SCH;WETEST_EX4) 4(;;LAY01)
The error "Cannot read properties of null (reading 'getLastFocusedRow')" appeared.
This problem now has been solved checking if the "enter" click event on keyboard rises from spotlight or from datatable.
=> LS25000589: Unchecked null EXU from spotlight

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/managers/kup-keys-binding/kup-keys-binding.ts
Resolved an error when, clicking on 'enter' on keyboard, event from datatable fires without having a right focused element.
=> LS25000589: unchecked null exu from spotlight 

packages/ketchup/src/components/kup-list/kup-list.tsx
With these changes the focus on kup-list global filter for combo has a retry mechanism to temporarely fix the issue of a missing focus on list open.
Note:
_The choice to use this approach has been made after unsuccesfully trying to apply the focus on Promise mechanism used in kup-text-field_
=> LS25000533: Focus on CMB with retry

packages/ketchup/src/managers/kup-data/kup-data.ts
An object without a shape but with maxLength>=256 caused to render the component automatically as a MEMO type, without checking the obj before.
The condition has been moved as last inside kup-data.
=> LS25000824: errori visualizzazione mobile

packages/ketchup/src/managers/kup-dynamic-position/kup-dynamic-position.ts
Wait until the tooltip has a real size before starting to calculate its position.
=> LS25000569 - fix: calc position tooltip after real size

packages/ketchup/src/f-components/f-cell/f-cell.scss
Fixed exb height when rows are empty inside a datatable.
=> LS25000824: errori visualizzazione mobile - fix exb height

packages/ketchup/src/components/kup-card/built-in/kup-card-message-box.tsx, packages/ketchup/src/components/kup-card/kup-card-declarations.ts
Added the ( optional ) possibility to add a custom label to both cancel and confirm to the messageBoxOptions by still mantaining the default ABORT and CONFIRM kupLanguage values if the relative prop is not found
=> LS25000834 : Card message box custom label

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx
Calculate a scroll to row offset in order to avoid the scrolled row being hidden under a multi line column title.
This offset is now being calculated by counting the \n occurrences in every column, keeping the higher count and adding one (replacing the - 1 used in scrollToRow method).
=> LS25000900 : fix : TBL scroll to row offset based on col escapes

packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx
Change made for the main objective of reintroducing the number formatting in labels for input legacy.
After these changes the thing that is directly checked is now only the object (removing the shape check in a method entered only when the shape is already a label).
Added the support for formattable types (dates, numbers and times) while always using the newly added FLabel.
The main problem was that getType method checked for both shape and object while giving priority to shape.
The shape, as i said before, is always a label so there will never be a celltype number (now that the CellShape.LABEL has rightfully been added to the getType method check)
=> LS25000949 : fix : InputPanel label rendering with value formatting

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx
Handled right column fixed in `kup-data-table` updating index calculation for class names
Reference to Action: LS25000895 - Colonne fisse in matrice 
Tested in webupjs with dev-link. 
I will open a  pull request with test updated as soon as this pr will be closed
=> LS25000895  - bugfix(kup-data-table): right column fixed

packages/ketchup/src/components/kup-card/kup-card.tsx
Fixed `KupCard.dialog()` to check the card's class list for resizability instead of using querySelector, which always returned null.
=> LS25000922 - fix: unresizabile tooltip

packages/ketchup/src/utils/filters/filters-rows.ts, packages/ketchup/src/utils/filters/filters-tree-items.ts, packages/ketchup/src/utils/filters/filters.ts
Corrected a typo, ! in the filters-rows if condition.
By now passing a boolean optional value to the isFilterCompliantForValue method now it can differentiate between:
- GlobalFilter: needs an "inclusion" match for the provided string
- ColumnFilter (checkbox with left click on col): needs an exact match
=> LS25001055 : fix : differentiated globalfilter and column filter

packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-autocomplete/kup-autocomplete.tsx, packages/ketchup/src/components/kup-list/kup-list.tsx, packages/ketchup/src/components/kup-list/readme.md
Fix on the AML component regarding the selection of the first element with the `Enter` key, caused by the lack of focus on the first element of the `kup-list`. 
A method has been added that is called upon the creation of the `kup-list`, setting the `focus` state to the first element.
Video:
https://youtu.be/TBTxvRA33mQ
=> LS25001091 - fix: AML focus on first element

packages/ketchup/src/components/kup-data-table/kup-data-table-declarations.ts, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/components/kup-date-picker/kup-date-picker.tsx, packages/ketchup/src/components/kup-time-picker/kup-time-picker.tsx, packages/ketchup/src/f-components/f-cell/f-cell.tsx
Added shortcut Ctrl+D in exu to duplicate cell value in column, only in filtered rows or all if there are no filters. 
Shortcut available for: AUTOCOMPLETE - COMBOBOX - TEXT - NUMBER - DATE - TIME.
=> LS25001308: exu duplicate value in col

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/managers/kup-manager/kup-manager.ts, packages/ketchup/src/managers/kup-perf-tuning/kup-perf-tuning-declarations.ts, packages/ketchup/src/managers/kup-perf-tuning/kup-perf-tuning.ts
It will be possible to set a limit on rows per page or cells per page. With the current settings, the limit is set to 1000 rows per page.
If you need to change the settings, update this code.
```js
this.perfTuning = new KupPerfTuning({
maxCellsPerPage: Number.MAX_VALUE,
maxRowsPerPage: 1000,
priority: KupPerfTuningPriority.ROWS_PER_PAGE,
});
```
=> LS25001380: kup-data-table: Added limit to rows per page

packages/ketchup/src/components/kup-autocomplete/kup-autocomplete-declarations.ts, packages/ketchup/src/components/kup-autocomplete/kup-autocomplete.tsx, packages/ketchup/src/components/kup-combobox/kup-combobox-declarations.ts, packages/ketchup/src/components/kup-combobox/kup-combobox.tsx, packages/ketchup/src/components/kup-input-panel/kup-input-panel-utils.ts, packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx, packages/ketchup/src/f-components/f-text-field/f-text-field.scss
This PR manages the soon-to-be-added new shapes in absolute layout INP (CMB and ACP)
The changes will enable the legacyLook prop passing from the main components to their respective text-field in order to have a consistent look with the other shapes.
Slightly increased the horizontal space occupied by the INP (adding a left additional multiplier).
This change is made to allow ACP and CMB to correctly display their full content regardless of their icon adding some size to the field.
Added an 18px size to ACP, CMB and DatePicker width to account for their icon size
Unified LAB, ITX, ACP, CMB and DatePicker calculations for their width to avoid confusion.
Lowered the precision of the calculations a bit in order to adapt it to every field
Additional length and shape considerations will also …
=> LS25001463 : feat : CMB and ACP shapes in absolute layout INP - Position and size managment

packages/ketchup/src/components/kup-autocomplete/kup-autocomplete.tsx, packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx
Changed AllowInconsistentValues prop default in order to have the web standards default ACP behaviour
=> LS25001568 : minor-fix : allowing inconsistent values in ACP

packages/ketchup/src/managers/kup-data/kup-data.ts
This pull request includes a small but important change to the `KupData` class in the `kup-data.ts` file. The change ensures that the `hasActionCell` method checks if the `cell` or `cell.obj` is null or undefined before proceeding with further logic.
* [`packages/ketchup/src/managers/kup-data/kup-data.ts`](diffhunk://#diff-1134f1c58f69c8c58f677c4b837309662d336de988a6c488cd0063c2125fcb31R304): Added a null check for `cell` and `cell.obj` in the `hasActionCell` method to prevent potential errors.
=> TKIC391491: kup-data-table: fix error on merge columns, without smeupObject

packages/ketchup/src/components/kup-card/built-in/kup-card-column-drop-menu.tsx, packages/ketchup/src/components/kup-card/kup-card-declarations.ts, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx
This pull request includes several changes to the `kup-card` and `kup-data-table` components in the `packages/ketchup` directory. The most important changes focus on improving the handling of new columns and the callback functions used in the `kup-card` component.
* [`packages/ketchup/src/components/kup-card/built-in/kup-card-column-drop-menu.tsx`](diffhunk://#diff-7166541362960452374dbd430b23bc6fa0c5eaab5d245a78c5611ddf38f95307L228-R228): Modified the `applyFormula` function to pass the `result` parameter to the `formulaCb` callback function. [[1]](diffhunk://#diff-7166541362960452374dbd430b23bc6fa0c5eaab5d245a78c5611ddf38f95307L228-R228) [[2]](diffhunk://#diff-7166541362960452374dbd430b23bc6fa0c5eaab5d245a78c5611ddf38f95307L243-R243) …
=> TKIC391491: kup-data-table: fix management new column with formula, added in to visibleColumns list

packages/ketchup/src/components/kup-input-panel/kup-input-panel-utils.ts, packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx
The absolute inp height calculation is now divided in 2 cases:
- With TBL: The rows of the TBL are now correctly considered as 20px, the remaining will be 22px as of before
- Without TBL: All the rows are considered 22px 
This avoids extra space when there is a tbl because her rows were considered of 22px as well, adding as much as 40 or 50 pixels of  extra empty space
=> NC : fix : absolute inp height calculations with TBL

packages/ketchup/src/components/kup-card/kup-card-helper.tsx, packages/ketchup/src/components/kup-card/standard/kup-card-standard-12.scss, packages/ketchup/src/components/kup-card/standard/kup-card-standard-14.scss, packages/ketchup/src/components/kup-card/standard/kup-card-standard.tsx, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/managers/kup-language/kup-language-declarations.ts, packages/ketchup/src/managers/kup-language/languages.json, packages/ketchup/src/managers/kup-manager/kup-manager.ts, packages/ketchup/src/managers/kup-perf-tuning/kup-perf-tuning-declarations.ts, packages/ketchup/src/managers/kup-perf-tuning/kup-perf-tuning.ts
- It will be displayed the first 200 checkboxes when opening the filtering card.
- Changed the logic to compute the maximum number of cells per page: if the number of columns is lower than 25, 1000 rows will be displayed; otherwise, (25000/columns) cells will be displayed.
=> LS25001762: kup-card: Performance optimizations

packages/ketchup/src/components/kup-autocomplete/kup-autocomplete.tsx, packages/ketchup/src/components/kup-combobox/kup-combobox.tsx
Set the title attribute to match the displayed value so that, when the displayed value exceeds the field length, the user can view the full description by hovering the mouse over the field.
=> LS25001851: kup-autocomplete/kup-combobox: Improved UX

packages/ketchup/src/components/kup-echart/kup-echart.tsx
This pull request makes updates to the `KupEchart` class in `kup-echart.tsx` to improve error handling and ensure proper resizing behavior. The changes focus on adding null checks and simplifying conditional logic.
* Updated the `disconnectedCallback` method to use optional chaining (`?.`) when calling `dispose` on `this.#chartEl`, preventing potential runtime errors if `#chartEl` is null or undefined.
* Modified the `resizeCallback` method to add a null check for `this.#chartEl.getZr()` before performing operations, ensuring the chart element is fully initialized. Simplified the logic for calculating `x` and `y` by removing unnecessary conditional checks.
=> kup-echart: fix automatic resize management, made it safer

packages/ketchup/src/components/kup-autocomplete/kup-autocomplete.tsx, packages/ketchup/src/components/kup-combobox/kup-combobox.tsx, packages/ketchup/src/f-components/f-text-field/f-text-field.tsx
- add clear icon logic on `kup-autocomplete` and `kup-combobox` 
- icon visibility depends on props `isClearable` and not empty value
=> feat/LS25001944: ACP and CMB onKupClearIconClick

packages/ketchup/package.json, yarn.lock
This pull request includes a small update to the `packages/ketchup/package.json` file. The change locks the version of the `@stencil/sass` dependency to `3.0.12` instead of using a version range (`^3`).
=> NC: re-created yarn.lock, update all dependencies

packages/ketchup/src/components/kup-autocomplete/kup-autocomplete.tsx
This pull request includes a small change to the `kup-autocomplete.tsx` file. The change removes the prevention of default behavior and event propagation when the 'Enter' key is pressed in the `KupAutocomplete` component.
=> LS25002312: kup-autocomplete: enter event management, without stop propagation

packages/ketchup/src/components/kup-editor/kup-editor.tsx, packages/ketchup/src/managers/kup-theme/kup-theme-application.scss
This pull request introduces enhancements to the `kup-editor` component in the `ketchup` package, focusing on improving user experience and visual styling. The key changes include adding a placeholder to the text area, dynamically setting its height, and updating the padding in the associated SCSS file.
* [`packages/ketchup/src/components/kup-editor/kup-editor.tsx`](diffhunk://#diff-b3b9c985ca61d2b64280dac8fadef2dbda530ecdeabdc3e1c91ee03cdf7abc83R629-R633): Added a placeholder with the text "Type your text here..." to the text area and introduced a dynamic height style based on the `editorHeight` property.
* [`packages/ketchup/src/managers/kup-theme/kup-theme-application.scss`](diffhunk://#diff-0d117788568cfbf8274942e4b58932c6a6b58eaa754ec00b74e5420f0704697eL2441-R2442): Updated the …
=> fix: TED style update

packages/ketchup/src/f-components/f-cell/f-cell.tsx
fix: apply danger text only when there isn't a custom color coming from backend
=> LS25002590 fix: custom color

packages/ketchup/src/f-components/f-cell/f-cell.tsx
This pull request refactors the `FCell` component in `f-cell.tsx` to improve readability and maintainability by reorganizing the initialization of `subcomponentProps`. The most important change involves moving the creation of `subcomponentProps` closer to its usage, ensuring better logical flow within the function.
Refactoring for improved readability:
* [`packages/ketchup/src/f-components/f-cell/f-cell.tsx`](diffhunk://#diff-55bfd4938b15230a3efa7bec67f01ff04fac25d96e76de1a5584c7ed5801813eL112-L119): Moved the initialization of `subcomponentProps` from its earlier position to directly before its usage, aligning it with the logical flow of the function. [[1]](diffhunk://#diff-55bfd4938b15230a3efa7bec67f01ff04fac25d96e76de1a5584c7ed5801813eL112-L119) …
=> LS25002976: kup-box: fix visualization of IMAGE in box, if calculated by default

packages/ketchup/src/f-components/f-cell/f-cell.tsx
Fixed adapter method to preserve options data order in radio button cell shape.
=> LS25002842: Options order

packages/ketchup/src/components/kup-autocomplete/kup-autocomplete.tsx, packages/ketchup/src/components/kup-combobox/kup-combobox.tsx
When size is specified, use the current size and ignore the list display mode behaviour
=> NC: feat: remove size when specified

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx, packages/ketchup/src/components/kup-data-table/styles/kup-data-table-main.scss
WARNING: this pr will break the actually present webupjs tests, a pr to fix those issues has been opened: [webupjs/1870](https://github.com/smeup/webup.js/pull/1870)
This PR changes the way EXU treats the click on the delete button.
Now instead of deleting the row only inside its data and confirming it with the submit button, the click directly triggers a kup-update event.
The payload is created to be identical to the payload created after an old delete and confirm process.
If only inserted AND NOT SUBMITTED rows are deleted there is no need to call an update. The method simply resort to the old deleteRows method
Added another small feature, a way to identify if a row has been inserted or modified:
- Inserted: green row background
- Modified: orange row background
=> feat / LS25003113 - EXU / delete action now triggers update

packages/ketchup/src/f-components/f-label/f-label.tsx
This PR introduces a small change to render all FLabel components as <span> elements instead of the default.
This adjustment is necessary because the surrounding fragment is a <div> with the class f-cell__content, not f-cell__text, which applies slightly different styles.
=> minor-fix: LS25003270: f-label

packages/ketchup/src/components/kup-data-table/kup-data-table-helper.ts, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx
This PR will make webupjs tests fail: fixed in this [PR](https://github.com/smeup/webup.js/pull/1927)
PR including changes regarding a new EXU insert mechanism, used to avoid problems when inserting a new row in an empty table:
- Keeping the graphic shapes, editability, size and maxLength of the column on insert
- When confirming the insert all the cells of the row are passed to webupjs and it's his responsibility to filter the ones that need to be sent to the *UPDATE service
The previous behaviour was to add only editable input fields cells even when editability was set to false or the shape was something other that an inputField
LS25003404: correggere editabilità in nuova riga exu
=> fix / LS25003404 / EXU insert with empty table now adds all the cells

packages/ketchup/src/components/kup-data-table/kup-data-table.tsx
This pull request makes a targeted fix to the `KupDataTable` component to improve its handling of the `originalData` property in emitted update events.
- Ensures that `originalData` falls back to the current `data` if `#originalDataLoaded` is undefined when emitting the `kupUpdate` event, preventing potential issues when the original data hasn't been loaded yet.
=> kup-data-table: fix creating list of updated data, if not updatetable - use for "otherButtons"

packages/ketchup/src/components/kup-chip/kup-chip-declarations.ts, packages/ketchup/src/components/kup-chip/kup-chip.tsx, packages/ketchup/src/f-components/f-chip/f-chip.scss, packages/ketchup/src/f-components/f-chip/f-chip.tsx
This pull request introduces several new properties and updates to the `kup-chip` component, enhancing its configurability and display options. The changes include new props for controlling chip behavior and appearance, adjustments to the order and documentation of existing props, and a minor style update for medium-sized chips.
**Component property enhancements:**
* Added new properties to `KupChipProps` and the `KupChip` class: `disabled`, `displayMode`, `label`, `sizing`, and `styling`, allowing for more flexible chip configuration and display. (`kup-chip-declarations.ts`, `kup-chip.tsx`) [[1]](diffhunk://#diff-a5aeefae75c4e2cc6f173464bb98da7cd9854b297ba8c49cd34b5d01d99f3f89L11-R17) [[2]](diffhunk://#diff-0a9306aeed5bf3771f4c8c32d429e55b4be8296ae3a1ff03c9623990ca8bb584L67-R85)
* …
=> LS25003361: kup-chip: managed font size sizing too, when change "sizing" prop

packages/ketchup/src/components.d.ts, packages/ketchup/src/components/kup-file-upload/kup-file-upload-declarations.ts, packages/ketchup/src/components/kup-file-upload/kup-file-upload.scss, packages/ketchup/src/components/kup-file-upload/kup-file-upload.tsx, packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx, packages/ketchup/src/f-components/f-cell/f-cell.tsx, packages/ketchup/src/managers/kup-language/kup-language-declarations.ts, packages/ketchup/src/managers/kup-language/languages.json
- Prevent adding multiple temporary files when multi-file mode is disabled
- Prevent duplicate file uploads
- Fix `pathString` prop update
- Enable automatic upload on drag-and-drop in auto-upload mode
- Add file extension validation on drop
- Restrict multiple file drops when multi-file mode is disabled
=> NC: Fix: kup-file-upload

packages/ketchup/src/f-components/f-image/f-image.tsx
This pull request makes a minor update to the `createImage` function in `f-image.tsx` to improve robustness when handling the `onLoad` event. The main change ensures that DOM queries and manipulations are only attempted if the image and its parent element exist, preventing potential runtime errors.
- Added a check to confirm that `img` and its `parentElement` exist before querying for and manipulating DOM elements in the `onLoad` handler. [[1]](diffhunk://#diff-73e55fc3c2c0c0e168c1b7ef0f9792f42f8c1d55991e90178fab582cf0670e7aR130-R140) [[2]](diffhunk://#diff-73e55fc3c2c0c0e168c1b7ef0f9792f42f8c1d55991e90178fab582cf0670e7aR152)
=> LS25003042: f-image: safe management create element

packages/ketchup/src/components/kup-input-panel/kup-input-panel.tsx
The Respective PRs on [kokos-sdk-java-rpgle](https://github.com/smeup/kokos-sdk-java-rpgle/pull/769) and [as400 proxy](https://github.com/smeup/kokos-me-java-as400proxy/pull/226) need to be approved before this one
This PR changes the way initial options are fetched and interpreted.
Now the data passed is in a Cell array format and not in an { id: ... , label: .... } format
=> fix: LS25003825: initial options as data cell

packages/ketchup/src/components/kup-data-table/kup-data-table-state.ts, packages/ketchup/src/components/kup-data-table/kup-data-table.tsx
This PR is a preparation for a bigger set of changes that will be released in webupjs.
This new pendingRowsToUpdate state will contain the rows that encountered an error when executing an exu UPDATE, but why not pass them directly in data?
Because they will be added into originalDataLoaded variable and into the kupUpdate payload, even if the backend update failed, ruining the BEFORE part of the fun with non-updated data.
=> feat: LS25003983: added pendingRowsToUpdate state attribute
